import sqlite3, json
from datetime import date
from pathlib import Path

BASE=Path(__file__).resolve().parent
DB=BASE/'opportunities.db'
TODAY='2026-08-30'

PLATFORMS=[
 dict(slug='british-council-learnenglish',name='British Council – LearnEnglish',description='منصة المجلس الثقافي البريطاني الرسمية لتعلم الإنجليزية عبر مواد وتمارين ومهارات متعددة. توجد موارد مجانية، بينما الشهادات الرسمية واختبارات اللغة تعتمد على البرنامج أو الاختبار ولا تُفترض مجانًا.',official_url='https://learnenglish.britishcouncil.org/',courses_url='https://learnenglish.britishcouncil.org/skills',certificates_url='https://www.britishcouncil.org/exam',country='UK / Global',categories=['English','Languages'],free_courses_available=1,certificates_available=1,financial_aid_available=0,free_access_guide='استخدم موارد LearnEnglish المجانية. لا تعتبر الشهادة الرسمية أو اختبار اللغة مجانيًا إلا إذا أعلن المصدر الرسمي ذلك للعرض المحدد.',official_source='https://learnenglish.britishcouncil.org/'),
 dict(slug='forage-virtual-experience',name='Forage – Virtual Experience Programs',description='منصة تجارب مهنية افتراضية تقدم برامج محاكاة للعمل من شركات وجهات معروفة. بعض البرامج تستهدف طلاب الثانوية، وتمنح شهادة إتمام عند استيفاء متطلبات البرنامج المحدد.',official_url='https://www.theforage.com/',courses_url='https://www.theforage.com/simulations',certificates_url='https://www.theforage.com/',country='Global / Online',categories=['Virtual Experience','Internship','Career Exploration'],free_courses_available=1,certificates_available=1,financial_aid_available=0,free_access_guide='البرامج الافتراضية المدرجة على Forage مجانية عادةً؛ تحقق من صفحة البرنامج نفسها للعمر والشهادة قبل التسجيل.',official_source='https://www.theforage.com/'),
 dict(slug='russian-open-doors',name='Open Doors – Russian Scholarship Project',description='مشروع المنح المفتوح التابع لـ Global Universities في روسيا، ويعلن دورات تنافسية للمتقدمين الدوليين للدراسة في الجامعات الروسية. الأهلية والمراحل تختلف حسب السنة والمستوى.',official_url='https://od.globaluni.ru/',courses_url='https://od.globaluni.ru/',certificates_url='https://od.globaluni.ru/',country='Russia',categories=['Russian Scholarships','Graduate','PhD'],free_courses_available=0,certificates_available=0,financial_aid_available=1,free_access_guide='راجع دورة Open Doors الحالية وشروط الفئة الدراسية والموعد من البوابة الرسمية؛ لا تعتمد على موعد قديم.',official_source='https://od.globaluni.ru/'),
 dict(slug='education-in-russia',name='Study in Russia – Government Information Portal',description='بوابة معلومات رسمية مرتبطة بوزارة التعليم والعلوم الروسية للطلاب الدوليين، تجمع معلومات عن الجامعات والقبول والمنح والمسارات الدراسية في روسيا.',official_url='https://studyinrussia.ru/',courses_url='https://studyinrussia.ru/',certificates_url='https://studyinrussia.ru/',country='Russia',categories=['Russia','Scholarships','Universities','International Students'],free_courses_available=0,certificates_available=0,financial_aid_available=1,free_access_guide='استخدمها كبوابة تحقق للوصول إلى معلومات الجامعات والمنح الرسمية في روسيا، ثم اتبع تعليمات الجامعة أو البرنامج نفسه.',official_source='https://studyinrussia.ru/'),
]

COURSES=[
 ('bc-english-listening','LearnEnglish – Listening','british-council-learnenglish','موارد استماع مجانية من المجلس الثقافي البريطاني بمستويات مختلفة، مع نصوص وأنشطة للممارسة الذاتية.','English / Languages','A1–C1','English','ذاتي',1,0,'لا توجد شهادة لغة مجانية عامة معلنة لهذا المورد','مجاني',0,'https://learnenglish.britishcouncil.org/skills/listening','official'),
 ('bc-english-reading','LearnEnglish – Reading','british-council-learnenglish','تمارين قراءة مجانية من British Council لمستويات متعددة مع مفردات وأسئلة فهم.','English / Languages','A1–C1','English','ذاتي',1,0,'لا توجد شهادة لغة مجانية عامة معلنة لهذا المورد','مجاني',0,'https://learnenglish.britishcouncil.org/skills/reading','official'),
 ('bc-english-speaking','LearnEnglish – Speaking','british-council-learnenglish','موارد مجانية لتطوير التحدث والعبارات والتواصل في مواقف مختلفة.','English / Languages','A1–C1','English','ذاتي',1,0,'لا توجد شهادة لغة مجانية عامة معلنة لهذا المورد','مجاني',0,'https://learnenglish.britishcouncil.org/skills/speaking','official'),
 ('goethe-deutsch-jugendliche','Goethe-Institut – Deutsch für Kinder und Jugendliche','goethe-free-german','مجموعة مجانية من تطبيقات وألعاب وفيديوهات وتمارين الألمانية الموجهة للأطفال والمراهقين، مع مستويات وأنشطة متنوعة.','German / Languages','A1–B2','German','ذاتي',1,0,'لا توجد شهادة Goethe-Zertifikat مجانية ضمن هذه الموارد','مجاني',0,'https://www.goethe.de/ueben','official'),
 ('goethe-mwd-a1-b2','Mein Weg nach Deutschland – Deutsch üben','goethe-free-german','تدريبات مجانية من Goethe-Institut من A1 إلى B2، تركز على الحياة اليومية والعمل والاندماج في ألمانيا.','German / Languages','A1–B2','German','ذاتي',1,0,'التدريب مجاني؛ امتحانات Goethe الرسمية منفصلة','مجاني',0,'https://www.goethe.de/prj/mwd/de/deu.html','official'),
 ('tv5-french-premiere-classe','TV5MONDE – Première classe','tv5monde-apprendre','مسار مجاني للمبتدئين في الفرنسية باستخدام الفيديو والأنشطة والمواقف اليومية.','French / Languages','A1','French','ذاتي',1,0,'لا توجد شهادة DELF/DALF مجانية ضمن TV5MONDE','مجاني',0,'https://apprendre.tv5monde.com/fr','official'),
 ('rfi-francais-facile','RFI Savoirs – Français facile','rfi-savoirs-french','تعلم الفرنسية من خلال الأخبار والملفات الصوتية والتمارين والمواد التفاعلية.','French / Languages','A1–C1','French','ذاتي',1,0,'لا توجد شهادة لغة رسمية مجانية عامة معلنة','مجاني',0,'https://savoirs.rfi.fr/fr/apprendre-enseigner','official'),
 ('irodori-japanese-a1','IRODORI – Japanese for Life in Japan','irodori-japanese','مواد مجانية رسمية لتعلم اليابانية العملية للحياة اليومية والعمل، مع كتب وملفات صوتية وأنشطة قابلة للتنزيل.','Japanese / Languages','A1–B1','Japanese','ذاتي',1,0,'لا توجد شهادة JLPT مجانية؛ JLPT امتحان منفصل','مجاني',0,'https://www.irodori.jpf.go.jp/en/','official'),
 ('nhk-easy-japanese','NHK WORLD-JAPAN – Easy Japanese','nhk-easy-japanese','دروس يابانية مجانية للمبتدئين عبر حوارات قصيرة ومفردات وملفات صوتية.','Japanese / Languages','مبتدئ','Japanese','ذاتي',1,0,'لا توجد شهادة مجانية عامة معلنة','مجاني',0,'https://www3.nhk.or.jp/nhkworld/en/learnjapanese/','official'),
 ('ksi-korean-1','Online King Sejong Institute – Korean 1','sejong-korean','مسار كوري رسمي للمبتدئين عبر Online King Sejong Institute. المواد متاحة مجانًا، وتوجد مسارات منظمة قد تمنح شهادة إتمام عند استيفاء شروط الحضور والواجبات والتقييم.','Korean / Languages','Beginner 1','Korean','دورة منظمة / ذاتية',1,1,'Certificate of Completion في المسارات المؤهلة فقط؛ لا يساوي إثبات لغة للفيزا','مجاني',0,'https://www.iksi.or.kr/lms/main/main.do?lang=EN','official'),
 ('ksi-korean-2','Online King Sejong Institute – Korean 2','sejong-korean','مسار كوري للمبتدئ المتقدم/المستوى الثاني ضمن Online KSI، مع تعلم إلكتروني من المصدر الرسمي.','Korean / Languages','Beginner 2','Korean','دورة منظمة / ذاتية',1,1,'Certificate of Completion في المسارات المؤهلة فقط','مجاني',0,'https://www.iksi.or.kr/lms/main/main.do?lang=EN','official'),
 ('pushkin-russian-learn','Pushkin Institute – Russian Learning','pushkin-russian','مواد ودورات رقمية لتعلم الروسية كلغة أجنبية من معهد بوشكين. تفاصيل الشهادة والرسوم تختلف حسب البرنامج.','Russian / Languages','Beginner–Advanced','Russian','متغير',1,1,'شهادة حسب البرنامج المحدد؛ لا نعممها على كل مادة مجانية','حسب البرنامج',0,'https://pushkininstitute.ru/learn','official'),
 ('cervantes-spanish-ave','Instituto Cervantes – AVE Global','cervantes-ave','منصة Instituto Cervantes الرسمية لتعلم الإسبانية وفق مستويات CEFR؛ الوصول والشهادة يختلفان حسب العرض الحالي.','Spanish / Languages','A1–C1','Spanish','متغير',0,1,'شهادة حسب المسار؛ DELE/SIELE امتحانات رسمية منفصلة','حسب الدورة',0,'https://ave.cervantes.es/','official'),
 ('rai-italiano','Rai Scuola – Italiano','rai-scuola-italiano','محتوى مجاني من Rai Scuola لتعلم وممارسة الإيطالية عبر فيديوهات وبرامج تعليمية.','Italian / Languages','Beginner–Intermediate','Italian','ذاتي',1,0,'لا توجد شهادة لغة رسمية مجانية عامة معلنة','مجاني',0,'https://www.raiscuola.rai.it/italiano','official'),
 ('yunus-emre-turkish','Yunus Emre – Turkish Resources','yunus-emre-turkish','موارد وبرامج رسمية لتعلم التركية والثقافة التركية. تختلف الشهادة والرسوم حسب المركز أو البرنامج.','Turkish / Languages','Beginner–Advanced','Turkish','متغير',1,1,'الشهادة حسب البرنامج؛ تحقق من المركز الرسمي','حسب البرنامج',0,'https://turkce.yee.org.tr/','official'),
 ('chineseplus-beginner','ChinesePlus – Chinese Learning','chineseplus','موارد رقمية لتعلم الصينية تشمل النطق والمفردات والاستماع والمواقف اليومية.','Chinese / Languages','Beginner','Chinese','ذاتي',1,0,'لا توجد شهادة عامة مجانية مؤكدة لكل المورد','مجاني حسب المورد',0,'https://www.chineseplus.net/','official'),
 ('openlearn-how-learn-language-2026','OpenLearn – How to learn a language','openlearn-languages','دورة مجانية من The Open University عن استراتيجيات تعلم اللغات. يمكن الحصول على Statement of Participation مجاني، وتتوفر شارة رقمية مجانية عند استيفاء متطلبات الشارة.','Language Learning','مبتدئ','English','حوالي 24 ساعة',1,1,'Open University Statement of Participation + Digital Badge عند استيفاء الشروط؛ ليست رصيدًا أكاديميًا','مجاني',0,'https://www.open.edu/openlearn/languages/how-learn-language','official'),
 ('openlearn-english-world-today','OpenLearn – English in the world today','openlearn-languages','دورة مجانية تشرح انتشار الإنجليزية عالميًا وتأثيرها الاجتماعي والسياسي. يحصل المتعلم على Statement of Participation عند الإتمام.','English / Languages','مبتدئ','English','حوالي 8 ساعات',1,1,'Open University Statement of Participation','مجاني',0,'https://www.open.edu/openlearn/languages/english-language/english-the-world-today/content-section-0','official'),
 ('openlearn-describing-language','OpenLearn – Describing language','openlearn-languages','دورة مجانية عن كيفية وصف اللغة وبنيتها واستخدامها، مع Statement of Participation وشارة رقمية في الدورات المؤهلة.','Language Learning','مبتدئ','English','متعدد الأسابيع',1,1,'Open University Statement of Participation + Digital Badge عند استيفاء الشروط','مجاني',0,'https://www.open.edu/openlearn/mod/oucontent/view.php?id=126712','official'),
 ('openlearn-english-skills-learning','OpenLearn – English: skills for learning','openlearn-languages','دورة مجانية لتنمية مهارات التعلم باللغة الإنجليزية، مع إثبات مشاركة مجاني وشارة رقمية عند استيفاء الشروط.','English / Languages','مبتدئ','English','متعدد الأسابيع',1,1,'Open University Statement of Participation + Digital Badge عند استيفاء الشروط','مجاني',0,'https://www.open.edu/openlearn/mod/oucontent/view.php?id=19418','official'),
 ('ibm-ai-literacy-multilang','IBM SkillsBuild – AI Literacy','ibm-skillsbuild','اعتماد رقمي من IBM SkillsBuild في أساسيات الذكاء الاصطناعي. الصفحة الرسمية تعرضه لجميع المتعلمين وبعدد كبير من اللغات، ومنها العربية والفرنسية والألمانية والإيطالية واليابانية والإسبانية والتركية والصينية التقليدية.','AI / Digital Skills','مبتدئ','Arabic / French / German / Italian / Japanese / Spanish / Turkish / Chinese وغيرها','حوالي 4 ساعات',1,1,'IBM SkillsBuild Digital Credential عبر Credly عند استيفاء النشاط المؤهل','مجاني',0,'https://skillsbuild.org/students/digital-credentials','official'),
 ('ibm-cybersecurity-multilang','IBM SkillsBuild – Cybersecurity Fundamentals','ibm-skillsbuild','اعتماد رقمي في أساسيات الأمن السيبراني من IBM SkillsBuild، مع لغات تشمل الهولندية والفرنسية والألمانية والإيطالية واليابانية والكورية والإسبانية والصينية والتركية وغيرها.','Cybersecurity / Digital Skills','مبتدئ','Multiple','حوالي 7.5 ساعات',1,1,'IBM SkillsBuild Digital Credential عبر Credly عند استيفاء النشاط المؤهل','مجاني',0,'https://skillsbuild.org/students/digital-credentials','official'),
]

OPPS=[
 dict(slug='forage-clifford-chance-ready-set-law-2026',type='internship',title='Clifford Chance – Ready, Set, Law',organization='Clifford Chance / Forage',description='تجربة مهنية افتراضية مجانية صممت لفئة 16–18 عامًا وتعرّف الطالب على العمل القانوني من خلال مهام ذاتية وتسجيلات وأمثلة إجابات. تمنح شهادة عند إكمال البرنامج.',country='Global / Online',online=1,age_min=16,age_max=18,education_level='Secondary / High School',category='Law / Career Exploration',language='English',funding_type='Free virtual experience',tuition_covered=1,certificate=1,duration='ذاتي',deadline=None,application_url='https://www.theforage.com/simulations/clifford-chance/ready-set-law-8vwx',official_source='https://www.theforage.com/simulations/clifford-chance/ready-set-law-8vwx',eligibility='مصمم لفئة 16–18 عامًا ومفتوح للجميع وفق صفحة البرنامج.',requirements='إكمال المهام والأنشطة المطلوبة في البرنامج؛ لا توجد خبرة قانونية مسبقة مطلوبة وفق الصفحة الرسمية.',required_documents='لا توجد مستندات تقديم تقليدية؛ التسجيل والوصول يتمان عبر المنصة.',application_steps='1) افتح صفحة البرنامج الرسمية. 2) أنشئ حساب Forage. 3) ابدأ المهام الذاتية. 4) أكمل متطلبات البرنامج لتحصل على الشهادة.',about_opportunity='تجربة مهنية افتراضية وليست وظيفة مدفوعة أو تدريبًا وظيفيًا لدى Clifford Chance. الهدف استكشاف المجال القانوني وبناء مهارات عملية.'),
 dict(slug='forage-slaughter-may-explore-law-2026',type='internship',title='Slaughter and May – Explore Law',organization='Slaughter and May / Forage',description='محاكاة مهنية افتراضية مجانية موجهة خصوصًا إلى طلاب 16–18 عامًا، وتشمل مهامًا في التحليل القانوني والبحث والعمل التجاري. يحصل المشارك على شهادة إتمام.',country='Global / Online',online=1,age_min=16,age_max=18,education_level='Secondary / High School',category='Law / Career Exploration',language='English',funding_type='Free virtual experience',tuition_covered=1,certificate=1,duration='4–5 ساعات ذاتية',deadline=None,application_url='https://www.theforage.com/simulations/slaughter-may/explore-law-beu6',official_source='https://www.theforage.com/simulations/slaughter-may/explore-law-beu6',eligibility='مفتوح للجميع ومصمم خصوصًا لفئة 16–18 عامًا.',requirements='لا تتطلب الصفحة خبرة قانونية سابقة؛ إكمال المهام المطلوبة.',required_documents='لا توجد مستندات تقديم تقليدية؛ التسجيل في Forage.',application_steps='1) افتح البرنامج. 2) سجل في Forage. 3) أكمل الوحدات والمهام. 4) احصل على شهادة الإتمام.',about_opportunity='محاكاة مهنية تعليمية وليست وظيفة أو تدريبًا مدفوعًا. مناسبة لاستكشاف القانون التجاري.'),
 dict(slug='forage-linklaters-business-teams-2026',type='internship',title='Linklaters – Introduction to Business Teams',organization='Linklaters / Forage',description='برنامج خبرة افتراضية مجاني مصمم لفئة 16–18 عامًا، يعرّف الطالب على التسويق والموارد البشرية والتقنية والعمليات القانونية والمالية. إكمال 3 وحدات يكفي للحصول على شهادة إتمام وفق الصفحة الرسمية.',country='Global / Online',online=1,age_min=16,age_max=18,education_level='Secondary / High School',category='Business / Technology / Law / Finance',language='English',funding_type='Free virtual experience',tuition_covered=1,certificate=1,duration='7–8 ساعات ذاتية',deadline=None,application_url='https://www.theforage.com/simulations/linklaters/intro-business-teams-uk-1q7y',official_source='https://www.theforage.com/simulations/linklaters/intro-business-teams-uk-1q7y',eligibility='مفتوح للطلاب ومصمم لفئة 16–18 عامًا.',requirements='إكمال 3 وحدات على الأقل للحصول على شهادة الإتمام وفق الصفحة الرسمية.',required_documents='لا توجد مستندات تقديم تقليدية.',application_steps='1) التسجيل في Forage. 2) اختيار الوحدات. 3) إكمال 3 وحدات على الأقل. 4) تنزيل/عرض الشهادة من المنصة.',about_opportunity='تجربة افتراضية لاستكشاف عدة فرق مهنية داخل شركة محاماة دولية، وليست وظيفة مدفوعة.'),
 dict(slug='open-doors-russian-scholarship-2026',type='scholarship',title='Open Doors – Russian Scholarship Project',organization='Global Universities / Russia',description='مسابقة/منحة أكاديمية للطلاب الدوليين للدراسة في روسيا ضمن الجامعات المشاركة. الفئات والمستويات والمواعيد تتغير حسب الدورة السنوية؛ يجب الاعتماد على بوابة Open Doors الحالية.',country='Russia',online=1,age_min=18,age_max=None,education_level='Master / PhD / Postgraduate',category='Scholarships / Russia',language='English / Russian',funding_type='Scholarship / tuition support according to current call',tuition_covered=1,certificate=None,duration='حسب البرنامج',deadline=None,application_url='https://od.globaluni.ru/',official_source='https://od.globaluni.ru/',eligibility='تختلف الأهلية حسب المسار والمستوى والدورة الحالية.',requirements='المؤهلات الأكاديمية والوثائق تختلف حسب المسار؛ راجع صفحة الدورة الحالية.',required_documents='يحددها المسار الحالي في بوابة Open Doors.',application_steps='1) افتح البوابة الرسمية. 2) اختر المسار الحالي. 3) راجع الأهلية والجدول الزمني. 4) أنشئ حسابًا. 5) أكمل مراحل المسابقة وارفع المستندات المطلوبة.',about_opportunity='فرصة روسية رسمية للطلاب الدوليين؛ لا نضع موعدًا ثابتًا في زاد لأن الدورة السنوية تتغير.'),
 dict(slug='study-in-russia-scholarships-portal-2026',type='scholarship',title='Study in Russia – Government Scholarship & Admission Portal',organization='Study in Russia',description='بوابة رسمية للطلاب الدوليين للبحث عن الدراسة في روسيا، مع معلومات عن الجامعات والقبول والمنح والمسارات الحكومية. استخدمها للوصول إلى الإعلان الحالي بدل الاعتماد على صفحات غير رسمية.',country='Russia',online=1,age_min=18,age_max=None,education_level='University / Graduate',category='Scholarships / University Admission',language='English / Russian',funding_type='Varies by university/program',tuition_covered=None,certificate=None,duration='حسب البرنامج',deadline=None,application_url='https://studyinrussia.ru/',official_source='https://studyinrussia.ru/',eligibility='تختلف حسب الجامعة والبرنامج والمنحة.',requirements='تختلف حسب الجامعة والبرنامج؛ يجب فحص المصدر المرتبط بكل برنامج.',required_documents='حسب الجامعة أو برنامج المنحة.',application_steps='1) ابحث عن البرنامج. 2) افتح صفحة الجامعة الرسمية. 3) تحقق من المنحة والموعد. 4) اتبع تعليمات الجامعة للتقديم.',about_opportunity='بوابة تحقق رسمية أكثر من كونها منحة واحدة؛ مفيدة للبحث عن فرص روسيا دون خلطها بمصادر تجميع غير رسمية.'),
 dict(slug='ibm-skillsbuild-highschool-2026',type='program',title='IBM SkillsBuild للمرحلة الثانوية – تعلم تقني واعتمادات رقمية',organization='IBM SkillsBuild',description='مسار رسمي لطلاب الثانوية بعمر 13–18، يقدم تعلمًا رقميًا مجانيًا في التقنية والمهارات المهنية، مع Digital Credentials في الأنشطة المؤهلة.',country='Global / Online',online=1,age_min=13,age_max=17,education_level='High School',category='AI / Cybersecurity / Data / Digital Skills',language='Multiple',funding_type='Free',tuition_covered=1,certificate=1,duration='متغير',deadline=None,application_url='https://skillsbuild.org/ar/high-school',official_source='https://skillsbuild.org/frequently-asked-questions?pageAction=openChat',eligibility='IBM توضح أن SkillsBuild للمرحلة الثانوية مصمم للمتعلمين بعمر 13 إلى 18؛ زاد يضعه ضمن 13–17 لفئة تحت 18.',requirements='إنشاء حساب وإكمال النشاط المؤهل للحصول على الاعتماد الرقمي عند توفره.',required_documents='لا توجد مستندات أكاديمية مطلوبة للتعلم الأساسي وفق صفحة التسجيل العامة.',application_steps='1) افتح الصفحة الرسمية. 2) اختر High School. 3) أنشئ حسابًا. 4) اختر المسار. 5) أكمل الأنشطة المؤهلة واعتمد الشارة عبر Credly عند توفرها.',about_opportunity='تعلم وتطوير مهني مجاني وليس وظيفة تدريبية مدفوعة. مناسب لمن يريد بناء سجل مهارات قبل الجامعة.'),
]


def upsert_platform(conn,p):
    conn.execute('''INSERT INTO platforms (slug,name,description,official_url,courses_url,certificates_url,scholarships_url,volunteering_url,country,categories,free_courses_available,certificates_available,financial_aid_available,free_access_guide,source_type,official_source,verified,last_checked)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,official_url=excluded.official_url,courses_url=excluded.courses_url,certificates_url=excluded.certificates_url,country=excluded.country,categories=excluded.categories,free_courses_available=excluded.free_courses_available,certificates_available=excluded.certificates_available,financial_aid_available=excluded.financial_aid_available,free_access_guide=excluded.free_access_guide,official_source=excluded.official_source,verified=1,last_checked=excluded.last_checked''',
    (p['slug'],p['name'],p['description'],p['official_url'],p.get('courses_url'),p.get('certificates_url'),p.get('scholarships_url'),p.get('volunteering_url'),p['country'],json.dumps(p['categories'],ensure_ascii=False),p['free_courses_available'],p['certificates_available'],p['financial_aid_available'],p['free_access_guide'],'official',p['official_source'],1,TODAY))

def add_course(conn,c):
    slug,title,pslug,desc,cat,level,lang,duration,free,cert,ctype,price,aid,url,source=c
    pid=conn.execute('SELECT id FROM platforms WHERE slug=?',(pslug,)).fetchone()
    if not pid: return
    conn.execute('''INSERT INTO courses (slug,title,platform_id,description,category,level,language,duration,free,certificate_available,certificate_type,price,financial_aid,official_url,source,source_type,verified,status,last_checked)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,description=excluded.description,category=excluded.category,level=excluded.level,language=excluded.language,duration=excluded.duration,free=excluded.free,certificate_available=excluded.certificate_available,certificate_type=excluded.certificate_type,price=excluded.price,financial_aid=excluded.financial_aid,official_url=excluded.official_url,source=excluded.source,source_type='official',verified=1,status='open',last_checked=excluded.last_checked''',
    (slug,title,pid[0],desc,cat,level,lang,duration,free,cert,ctype,price,aid,url,url,source,1,'open',TODAY))

def add_opp(conn,o):
    conn.execute('''INSERT INTO opportunities (slug,type,title,organization,description,country,online,age_min,age_max,education_level,category,language,funding_type,tuition_covered,certificate,duration,deadline,application_url,official_source,source_type,verified,status,last_checked,eligibility,requirements,required_documents,application_steps,about_opportunity,keywords)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(slug) DO UPDATE SET title=excluded.title,description=excluded.description,organization=excluded.organization,country=excluded.country,online=excluded.online,age_min=excluded.age_min,age_max=excluded.age_max,education_level=excluded.education_level,category=excluded.category,language=excluded.language,funding_type=excluded.funding_type,tuition_covered=excluded.tuition_covered,certificate=excluded.certificate,duration=excluded.duration,deadline=excluded.deadline,application_url=excluded.application_url,official_source=excluded.official_source,verified=1,status=excluded.status,last_checked=excluded.last_checked,eligibility=excluded.eligibility,requirements=excluded.requirements,required_documents=excluded.required_documents,application_steps=excluded.application_steps,about_opportunity=excluded.about_opportunity,keywords=excluded.keywords''',
    (o['slug'],o['type'],o['title'],o['organization'],o['description'],o['country'],o['online'],o.get('age_min'),o.get('age_max'),o['education_level'],o['category'],o['language'],o['funding_type'],o.get('tuition_covered'),o.get('certificate'),o.get('duration'),o.get('deadline'),o['application_url'],o['official_source'],'official',1,'open',TODAY,o.get('eligibility'),o.get('requirements'),o.get('required_documents'),o.get('application_steps'),o.get('about_opportunity'),o.get('keywords')))

def main():
    conn=sqlite3.connect(DB)
    try:
        for p in PLATFORMS: upsert_platform(conn,p)
        for c in COURSES: add_course(conn,c)
        for o in OPPS: add_opp(conn,o)
        conn.commit()
        print('catalog updated', conn.execute('select count(*) from platforms').fetchone()[0], conn.execute('select count(*) from courses').fetchone()[0], conn.execute('select count(*) from opportunities').fetchone()[0])
    finally: conn.close()
if __name__=='__main__': main()
