"""Additional official opportunities with cycle-dependent fields left open."""

ADDITIONAL_OPPORTUNITIES = [
    ("sch-add-commonwealth", "scholarship", "Commonwealth Master's Scholarships", "Commonwealth Scholarship Commission", "منحة للدراسات العليا للطلاب من دول الكومنولث المؤهلة.", "United Kingdom / Commonwealth", False, "Graduate", "Master", "English", "Fully Funded / varies", "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/"),
    ("sch-add-chevening", "scholarship", "Chevening Scholarships", "UK Foreign, Commonwealth & Development Office", "منحة حكومية بريطانية للدراسة بدوام كامل في برامج الماجستير للقيادات الدولية.", "United Kingdom / Global", False, "Graduate", "Leadership / Master", "English", "Fully Funded", "https://www.chevening.org/scholarships/"),
    ("sch-add-erasmus", "scholarship", "Erasmus Mundus Joint Masters", "European Commission", "برامج ماجستير مشتركة بين جامعات أوروبية مع منح تختلف حسب البرنامج.", "Europe / Global", False, "Graduate", "Master", "Multiple", "Scholarship / varies", "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en"),
    ("sch-add-daad", "scholarship", "DAAD Scholarship Database", "DAAD", "قاعدة رسمية للمنح وبرامج الدراسة والبحث في ألمانيا للطلاب والباحثين الدوليين.", "Germany / Global", False, "University / Graduate / Research", "Study / Research", "Multiple", "Varies", "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/"),
    ("sch-add-australia-awards", "scholarship", "Australia Awards Scholarships", "Australian Government", "منح حكومية أسترالية للدراسة والتنمية المهنية للمرشحين من الدول المشاركة.", "Australia / Participating countries", False, "Graduate / Professional", "Study / Development", "English", "Fully Funded / varies", "https://www.dfat.gov.au/people-to-people/australia-awards"),
    ("sch-add-new-zealand", "scholarship", "Manaaki New Zealand Scholarships", "New Zealand Government", "منح حكومية للدراسة في نيوزيلندا للمرشحين من الدول المؤهلة.", "New Zealand / Participating countries", False, "University / Graduate", "Study", "English", "Fully Funded / varies", "https://www.nzscholarships.govt.nz/"),
    ("sch-add-jica", "scholarship", "JICA Scholarships and Training", "Japan International Cooperation Agency", "فرص منح وتدريب مرتبطة ببرامج التعاون الدولي الياباني، وتختلف حسب الدولة والنداء.", "Japan / Participating countries", False, "Graduate / Professional", "Development / Research", "English / Japanese", "Varies", "https://www.jica.go.jp/english/our_work/types_of_assistance/oda_loans/tech/"),
    ("sch-add-rotary", "scholarship", "Rotary Peace Fellowship", "Rotary International", "زمالة للدراسات العليا في مجالات السلام والتنمية في مراكز Rotary المشاركة.", "Global", False, "Graduate", "Peace / Development", "English", "Fully Funded / varies", "https://www.rotary.org/en/our-programs/peace-fellowships"),
    ("sch-add-yale-young", "scholarship", "Yale Young Global Scholars", "Yale University", "برنامج أكاديمي صيفي عالمي لطلاب المرحلة الثانوية مع مساعدات مالية حسب الأهلية.", "USA / Global", False, "Secondary", "Leadership / Academics", "English", "Financial aid available", "https://globalscholars.yale.edu/"),
    ("sch-add-oxford-reach", "scholarship", "Reach Oxford Scholarship", "University of Oxford", "منحة للطلاب من الدول منخفضة الدخل الراغبين في الدراسة الجامعية في أكسفورد.", "United Kingdom", False, "Undergraduate", "Study", "English", "Fully Funded / varies", "https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship"),
    ("program-add-unicef", "program", "UNICEF Online Learning", "UNICEF Agora", "تعلم إلكتروني وموارد تدريبية رسمية في مجالات التنمية والعمل الإنساني وحقوق الطفل.", "Global", True, "Students / Professionals", "Development / Humanitarian", "Multiple", "Free / varies", "https://agora.unicef.org/"),
    ("program-add-un-campus", "program", "UN Campus", "United Nations System Staff College", "دورات وموارد تعلم إلكتروني تابعة لمنظومة الأمم المتحدة، مع اختلاف الإتاحة حسب الدورة.", "Global", True, "Students / Professionals", "Sustainable Development", "Multiple", "Free / varies", "https://www.unssc.org/courses"),
    ("program-add-google-cloud", "program", "Google Cloud Skills Boost", "Google Cloud", "مختبرات ومسارات عملية في السحابة والبيانات والذكاء الاصطناعي، وتختلف الإتاحة والشارات حسب العرض.", "Global", True, "Students / Professionals", "Cloud / AI / Data", "English", "Free / varies", "https://www.cloudskillsboost.google/"),
    ("program-add-meta-cert", "program", "Meta Blueprint Learning", "Meta", "تعلم رسمي في التسويق الرقمي والإعلانات والقياس والتجارة الإلكترونية.", "Global", True, "Students / Professionals", "Digital Marketing", "Multiple", "Free learning / paid exams", "https://www.facebook.com/business/learn"),
    ("competition-add-google-science", "competition", "Google Science Fair Resources", "Google", "موارد ومسارات رسمية تساعد الطلاب على تطوير مشاريع علمية وتقنية؛ توفر المسابقات يتغير حسب الدورة.", "Global", True, "Secondary", "Science / Technology", "English", "Free program / varies", "https://www.google.com/intl/en_us/edu/sciencefair/"),
]