import sqlite3, json
from datetime import datetime, timezone
DB='/mnt/data/zaad_project/opportunities.db'; TODAY=datetime.now(timezone.utc).date().isoformat()
conn=sqlite3.connect(DB)
platforms=[
('aws-skill-builder','AWS Skill Builder','منصة AWS الرسمية للتدريب الرقمي، وتوفر حسابًا مجانيًا يتيح مئات الدورات الرقمية وخطط التعلم وبعض الشارات والموارد المجانية.','https://skillbuilder.aws/','https://skillbuilder.aws/','https://skillbuilder.aws/','Global',['Cloud','AI','AWS'],1,1,'ابدأ بحساب AWS Skill Builder المجاني. لا تفترض أن كل المختبرات أو جميع الاعتمادات المهنية مجانية؛ تحقق من صفحة المورد قبل البدء.'),
('nvidia-dli','NVIDIA Deep Learning Institute','منصة NVIDIA الرسمية للتدريب في الذكاء الاصطناعي والتعلم العميق وعلوم البيانات والحوسبة المسرعة. توفر دورات ذاتية وبعض الدورات المجانية، بينما الشهادة متاحة في دورات مختارة فقط.','https://learn.nvidia.com/deep-learning-institute','https://learn.nvidia.com/en-us/training/self-paced-courses','https://learn.nvidia.com/deep-learning-institute','Global',['AI','Deep Learning','Data Science','GPU'],1,1,'يوفر برنامج NVIDIA Developer Program وصولًا إلى دورة DLI ذاتية مجانية، كما توجد دورات مجانية أخرى في الكتالوج. الشهادة ليست مضمونة لكل دورة؛ تحقق من وصف الدورة.'),
]
for slug,name,desc,official,courses,certs,country,cats,free,cert,guide in platforms:
 conn.execute('''INSERT INTO platforms (slug,name,description,official_url,courses_url,certificates_url,scholarships_url,volunteering_url,country,categories,free_courses_available,certificates_available,financial_aid_available,free_access_guide,official_source,verified,last_checked) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,official_url=excluded.official_url,courses_url=excluded.courses_url,certificates_url=excluded.certificates_url,country=excluded.country,categories=excluded.categories,free_courses_available=excluded.free_courses_available,certificates_available=excluded.certificates_available,free_access_guide=excluded.free_access_guide,last_checked=excluded.last_checked''',(slug,name,desc,official,courses,certs,official,official,country,json.dumps(cats),free,cert,0,guide,official,1,TODAY))
platform_ids={r[0]:r[1] for r in conn.execute("select slug,id from platforms where slug in ('aws-skill-builder','nvidia-dli')")}
courses=[
('aws-free-digital-training','AWS Skill Builder — Free Digital Training','aws-skill-builder','دورات رقمية مجانية من AWS تغطي أساسيات السحابة والذكاء الاصطناعي وخدمات AWS. صفحة الاشتراك الرسمية تذكر أن الحساب المجاني يتيح مئات الدورات الرقمية وخطط التعلم، مع اختلاف الوصول إلى المختبرات والاعتمادات حسب المورد.','الحوسبة السحابية','مبتدئ','متعدد اللغات','متغير',1,1,'AWS Digital Badge حسب خطة التعلم المؤهلة؛ ليس كل محتوى يمنح شارة','مجاني للحساب والمحتوى المجاني؛ بعض المختبرات/الخدمات لها شروط أو تكلفة','https://skillbuilder.aws/'),
('aws-cloud-quest-free-foundational','AWS Cloud Quest — مسارات تأسيسية مجانية','aws-skill-builder','تجربة تعلم تفاعلية في AWS Cloud Quest. المصدر الرسمي الحالي يذكر أن المسارين التأسيسيين متاحان مجانًا مع حساب Skill Builder، وأن التقدم يمكن أن يمنح شارات AWS رسمية.','AWS Cloud Quest','مبتدئ','الإنجليزية','متغير',1,1,'AWS Digital Badge حسب المسار','مجاني للمسارين التأسيسيين المذكورين حاليًا','https://docs.cloudquest.skillbuilder.aws/coming-soon/index.html'),
('nvidia-free-dli-self-paced','NVIDIA DLI — Free Self-Paced Course','nvidia-dli','تدريب ذاتي مجاني من NVIDIA Deep Learning Institute. NVIDIA تذكر أن الانضمام إلى Developer Program يفتح دورة DLI ذاتية مجانية، إضافة إلى وجود قسم Free Self-Paced Courses. بعض الدورات المختارة تمنح شهادة كفاءة.','الذكاء الاصطناعي','مبتدئ إلى متوسط','الإنجليزية','متغير',1,1,'NVIDIA DLI Certificate في الدورات المختارة فقط','مجاني للدورة المجانية المتاحة عبر Developer Program؛ تحقق من الشهادة لكل مقرر','https://learn.nvidia.com/en-us/training/self-paced-courses?section=self-paced-courses&tab=generative-ai-llm'),
]
for slug,title,pslug,desc,cat,level,lang,dur,free,cert,ctype,price,url in courses:
 conn.execute('''INSERT INTO courses (slug,title,platform_id,description,category,level,language,duration,free,certificate_available,certificate_type,price,financial_aid,official_url,source,source_type,verified,status,last_checked) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,description=excluded.description,category=excluded.category,level=excluded.level,language=excluded.language,duration=excluded.duration,free=excluded.free,certificate_available=excluded.certificate_available,certificate_type=excluded.certificate_type,price=excluded.price,official_url=excluded.official_url,source=excluded.source,last_checked=excluded.last_checked''',(slug,title,platform_ids[pslug],desc,cat,level,lang,dur,free,cert,ctype,price,0,url,url,'official',1,'open',TODAY))
conn.commit(); conn.close(); print('AWS/NVIDIA additions saved')
