import sqlite3, json, re
from pathlib import Path
DB=Path('opportunities.db')
TODAY='2026-08-30'
conn=sqlite3.connect(DB)
conn.row_factory=sqlite3.Row

def platform_id(slug):
    r=conn.execute('select id from platforms where slug=?',(slug,)).fetchone()
    return r['id'] if r else None

def add_platform(p):
    exists=conn.execute('select id from platforms where slug=?',(p['slug'],)).fetchone()
    if exists: return exists['id']
    conn.execute('''insert into platforms (slug,name,logo,description,official_url,courses_url,certificates_url,scholarships_url,volunteering_url,country,categories,free_courses_available,certificates_available,financial_aid_available,free_access_guide,source_type,official_source,verified,last_checked)
    values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(
        p['slug'],p['name'],None,p['description'],p['official_url'],p.get('courses_url'),p.get('certificates_url'),p.get('scholarships_url'),p.get('volunteering_url'),p.get('country','Global'),json.dumps(p.get('categories',[]),ensure_ascii=False),int(p.get('free_courses_available',1)),int(p.get('certificates_available',0)),int(p.get('financial_aid_available',0)),p.get('free_access_guide'), 'official',p['official_source'],1,TODAY))
    return conn.execute('select id from platforms where slug=?',(p['slug'],)).fetchone()['id']

def add_course(c):
    if conn.execute('select id from courses where slug=?',(c['slug'],)).fetchone(): return False
    conn.execute('''insert into courses (slug,title,platform_id,description,category,level,language,duration,free,certificate_available,certificate_type,price,financial_aid,official_url,source,source_type,verified,status,last_checked)
    values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(
        c['slug'],c['title'],c['platform_id'],c['description'],c['category'],c.get('level','Beginner'),c.get('language','Multiple'),c.get('duration','Self-paced'),int(c.get('free',1)),int(c.get('certificate_available',0)),c.get('certificate_type'),c.get('price','Free'),int(c.get('financial_aid',0)),c['official_url'],c.get('source',c['official_url']),'official',1,'open',TODAY))
    return True

def add_opp(o):
    if conn.execute('select id from opportunities where slug=?',(o['slug'],)).fetchone(): return False
    fields=['slug','type','title','organization','description','country','online','age_min','age_max','education_level','category','language','funding_type','tuition_covered','accommodation','meals','travel','stipend','duration','certificate','deadline','application_url','official_source','source_type','verified','status','last_checked','amount','awards','start_date','timezone','recurring_type','recurring_value','expired_at','eligibility','requirements','required_documents','application_steps','about_opportunity','keywords']
    vals=[o.get(k) for k in fields]
    conn.execute('insert into opportunities ('+','.join(fields)+') values ('+','.join('?'*len(fields))+')',vals)
    return True

# New official platforms. These complement existing entries; no old records are deleted.
platforms=[
 {'slug':'nasa-citizen-science','name':'NASA Citizen Science','description':'بوابة NASA الرسمية لمشاريع علم المواطن: المساهمة في أبحاث حقيقية في الفضاء والأرض والمناخ والبيانات. NASA توضح أن العمر ليس عائقًا عامًا، مع اختلاف شروط كل مشروع.','official_url':'https://science.nasa.gov/citizen-science/','courses_url':'https://science.nasa.gov/citizen-science/','certificates_url':None,'volunteering_url':'https://science.nasa.gov/citizen-science/','country':'USA / Global','categories':['NASA','Citizen Science','Science','Space'],'free_courses_available':1,'certificates_available':0,'free_access_guide':'المشاركة في مشاريع علم المواطن مجانية. افتح المشروع وتحقق من متطلبات العمر والتسجيل الخاصة به قبل البدء.','official_source':'https://science.nasa.gov/citizen-science/'},
 {'slug':'unicef-agora','name':'UNICEF Agora','description':'منصة UNICEF الرسمية للتعلم المفتوح للعامة والشركاء، تضم مئات فرص التعلم في العمل الإنساني والتنمية والصحة والطفولة والمهارات، ومعظم الأنشطة تتضمن تتبع إكمال وقد توفر شهادة إتمام أو شارة رقمية.','official_url':'https://agora.unicef.org/','courses_url':'https://agora.unicef.org/','certificates_url':'https://agora.unicef.org/','country':'Global / Online','categories':['UNICEF','Humanitarian','Development','Child Rights'],'free_courses_available':1,'certificates_available':1,'free_access_guide':'التسجيل مجاني ومفتوح للعامة. افحص كل نشاط لمعرفة هل يمنح شهادة أو شارة إتمام.','official_source':'https://agora.unicef.org/'},
]
for p in platforms: add_platform(p)

# Existing platform ids
P={s:platform_id(s) for s in ['google-for-education','google-skillshop','ibm-skillsbuild','harvard-cs50','aws','cisco-networking-academy','openlearn-languages','tv5monde-apprendre','rfi-savoirs-french','goethe-free-german','nhk-easy-japanese','cervantes-ave','rai-scuola-italiano','pushkin-russian','sejong-korean','chineseplus','rug-language-centre','navoica-polish-plus','zooniverse','nasa-citizen-science','unicef-agora','google','microsoft-learn']}
# fallback if duplicate platform slug isn't present, find by name
for k in list(P):
 if P[k] is None:
  pass

courses=[
 # Google / IBM / global credentials
 {'slug':'google-gemini-certified-student-k12','title':'Gemini Certified Student – K-12','platform_id':P['google-for-education'],'description':'شهادة Google رسمية للطلاب تحت 18. الصفحة الرسمية تذكر أنها مجانية، صالحة 3 سنوات، والامتحان متاح للطلاب من عمر 13+.','category':'AI / Generative AI','level':'Student','language':'English','duration':'Self-paced + exam','free':1,'certificate_available':1,'certificate_type':'Google certificate + badge (official)','official_url':'https://edu.google.com/learning-center/certifications/'},
 {'slug':'google-gemini-certified-student-university','title':'Gemini Certified Student – University','platform_id':P['google-for-education'],'description':'شهادة Gemini الرسمية من Google لطلاب الجامعة 18+، مجانية بحسب صفحة Google for Education، وصالحة 3 سنوات.','category':'AI / Generative AI','level':'University','language':'English','duration':'Self-paced + exam','free':1,'certificate_available':1,'certificate_type':'Google certificate + badge (official)','official_url':'https://edu.google.com/learning-center/certifications/'},
 {'slug':'google-certified-educator-level-1','title':'Google Certified Educator Level 1','platform_id':P['google-for-education'],'description':'اعتماد Google رسمي للمعلمين يثبت إتقان أدوات Google for Education؛ الامتحان والشهادة مذكوران كـ Free of charge على الصفحة الرسمية.','category':'Education / Google Workspace','level':'Educator','language':'Multiple','duration':'Self-paced + exam','free':1,'certificate_available':1,'certificate_type':'Google Certified Educator Level 1','official_url':'https://edu.google.com/learning-center/certifications/'},
 {'slug':'google-certified-educator-level-2','title':'Google Certified Educator Level 2','platform_id':P['google-for-education'],'description':'اعتماد Google رسمي متقدم للمعلمين، والصفحة الرسمية تذكر أنه مجاني وصالح 3 سنوات.','category':'Education / Google Workspace','level':'Advanced','language':'Multiple','duration':'Self-paced + exam','free':1,'certificate_available':1,'certificate_type':'Google Certified Educator Level 2','official_url':'https://edu.google.com/learning-center/certifications/'},
 {'slug':'google-ads-search-certification','title':'Google Ads Search Certification','platform_id':P['google-skillshop'],'description':'مسار تدريب واختبار اعتماد رسمي من Google Ads. التدريب مجاني والاعتماد يتم عبر Skillshop.','category':'Digital Marketing / Google Ads','level':'Beginner','language':'English','duration':'Self-paced','free':1,'certificate_available':1,'certificate_type':'Google Ads Certification','official_url':'https://skillshop.withgoogle.com/googleads/'},
 {'slug':'ibm-ai-fundamentals-digital-credential','title':'IBM AI Fundamentals – Digital Credential','platform_id':P['ibm-skillsbuild'],'description':'شهادة رقمية من IBM SkillsBuild في أساسيات الذكاء الاصطناعي. المنصة تذكر أن التعلم مجاني وأن الشهادات الرقمية تمنح عند إكمال النشاط الذي يقدمها.','category':'AI','level':'Beginner','language':'Arabic / English / French / German / Japanese / Spanish / Turkish / Chinese','duration':'10+ hours','free':1,'certificate_available':1,'certificate_type':'IBM SkillsBuild digital credential','official_url':'https://skillsbuild.org/ar/digital-credentials'},
 {'slug':'ibm-cybersecurity-fundamentals-digital-credential','title':'IBM Cybersecurity Fundamentals – Digital Credential','platform_id':P['ibm-skillsbuild'],'description':'مسار IBM في أساسيات الأمن السيبراني مع شهادة رقمية، ومتاح بلغات متعددة منها العربية والفرنسية والألمانية والهولندية والإيطالية واليابانية والكورية والبولندية والإسبانية والتركية.','category':'Cybersecurity','level':'Beginner','language':'Multiple','duration':'7.5 hours','free':1,'certificate_available':1,'certificate_type':'IBM SkillsBuild digital credential','official_url':'https://skillsbuild.org/ar/digital-credentials'},
 {'slug':'ibm-data-fundamentals-digital-credential','title':'IBM Data Fundamentals – Digital Credential','platform_id':P['ibm-skillsbuild'],'description':'شهادة رقمية من IBM في أساسيات البيانات ومحو الأمية البياناتية.','category':'Data / Analytics','level':'Beginner','language':'English / Arabic / French / German / Japanese / Spanish / Turkish','duration':'7 hours','free':1,'certificate_available':1,'certificate_type':'IBM SkillsBuild digital credential','official_url':'https://skillsbuild.org/ar/digital-credentials'},
 {'slug':'ibm-emerging-tech-digital-credential','title':'IBM Emerging Technologies – Digital Credential','platform_id':P['ibm-skillsbuild'],'description':'شهادة رقمية من IBM تغطي التقنيات الناشئة مثل الذكاء الاصطناعي والبيانات والحوسبة السحابية والحوسبة الكمومية.','category':'Emerging Technology','level':'Beginner','language':'Multiple','duration':'7+ hours','free':1,'certificate_available':1,'certificate_type':'IBM SkillsBuild digital credential','official_url':'https://skillsbuild.org/ar/digital-credentials'},
 {'slug':'openlearn-statement-of-participation','title':'OpenLearn Free Courses + Statement of Participation','platform_id':P['openlearn-languages'],'description':'دورات OpenLearn المجانية. بعد إكمال الدورة واستيفاء المتطلبات يمكن تنزيل Statement of Participation مجاني من Open University. إنشاء الحساب متاح من 13+.','category':'General Education / Languages','level':'All Levels','language':'English','duration':'Varies','free':1,'certificate_available':1,'certificate_type':'Open University Statement of Participation (free; not formal academic credit)','official_url':'https://www.open.edu/openlearn/about-openlearn/frequently-asked-questions-on-openlearn'},
 {'slug':'openlearn-children-youth-participation','title':'Children and Young People’s Participation','platform_id':P['openlearn-languages'],'description':'دورة مجانية من OpenLearn عن مشاركة الأطفال والشباب، وتمنح Statement of Participation مجانيًا عند الإكمال.','category':'Education / Youth','level':'Beginner','language':'English','duration':'Self-paced','free':1,'certificate_available':1,'certificate_type':'Free Statement of Participation','official_url':'https://www.open.edu/openlearn/education-development/childhood-youth/children-and-young-peoples-participation'},
 {'slug':'harvard-cs50x-free-certificate','title':'CS50x – Introduction to Computer Science','platform_id':P['harvard-cs50'],'description':'مقرر Harvard CS50x المجاني عبر الإنترنت. يمكن للمتعلم المؤهل الحصول على شهادة CS50 وفق متطلبات المقرر؛ شهادة edX الموثقة منفصلة ومدفوعة.','category':'Computer Science','level':'Beginner','language':'English','duration':'Self-paced','free':1,'certificate_available':1,'certificate_type':'CS50 certificate (free); edX verified certificate is separate','official_url':'https://cs50.harvard.edu/x/'},
 # Language resources, no false certificate claims
 {'slug':'tv5monde-apprendre-francais-a1-b2','title':'TV5MONDE – Apprendre le français A1–B2','platform_id':P['tv5monde-apprendre'],'description':'آلاف التمارين المجانية لتعلم الفرنسية من فيديوهات حقيقية، من المبتدئ إلى المتقدم، مع اختبار تحديد مستوى ومواد للقواعد والمفردات والتدرب على TCF.','category':'French','level':'A1–B2','language':'French / Arabic interface','duration':'Self-paced','free':1,'certificate_available':0,'certificate_type':'لا توجد شهادة مجانية عامة معلنة على صفحة المنصة','official_url':'https://apprendre.tv5monde.com/'},
 {'slug':'rfi-savoirs-francais-facile','title':'RFI Savoirs – Français facile','platform_id':P['rfi-savoirs-french'],'description':'موارد رسمية من RFI لتعلم الفرنسية عبر الأخبار والتمارين والاستماع والمواد التعليمية.','category':'French','level':'A1–B2','language':'French','duration':'Self-paced','free':1,'certificate_available':0,'certificate_type':'لا توجد شهادة مجانية عامة مثبتة هنا','official_url':'https://savoirs.rfi.fr/fr/apprendre-enseigner'},
 {'slug':'goethe-free-german-practice','title':'Goethe-Institut – Deutsch üben','platform_id':P['goethe-free-german'],'description':'تمارين وموارد مجانية من Goethe-Institut لممارسة الألمانية بمستويات مختلفة. الشهادات الرسمية Goethe-Zertifikat مرتبطة باختبارات منفصلة وليست مفترضة مجانًا.','category':'German','level':'A1–C1','language':'German','duration':'Self-paced','free':1,'certificate_available':0,'certificate_type':'الشهادة الرسمية عبر اختبار Goethe منفصل','official_url':'https://www.goethe.de/en/spr/ueb.html'},
 {'slug':'nhk-easy-japanese-course','title':'NHK WORLD-JAPAN – Easy Japanese','platform_id':P['nhk-easy-japanese'],'description':'دروس يابانية مجانية مبنية على مواقف يومية، مع صوت ونصوص ومواد للمبتدئين.','category':'Japanese','level':'Beginner','language':'Japanese / English','duration':'Self-paced','free':1,'certificate_available':0,'official_url':'https://www3.nhk.or.jp/nhkworld/en/learnjapanese/'},
 {'slug':'cervantes-spanish-resources','title':'Instituto Cervantes – Spanish Learning Resources','platform_id':P['cervantes-ave'],'description':'موارد رسمية من Instituto Cervantes لتعلم الإسبانية. الشهادات الرسمية DELE وSIELE لها إجراءات واختبارات منفصلة.','category':'Spanish','level':'A1–C1','language':'Spanish','duration':'Self-paced / varies','free':1,'certificate_available':0,'certificate_type':'DELE/SIELE منفصلة عن الموارد المجانية','official_url':'https://www.cervantes.es/lengua_y_ensenanza/aprender_espanol.htm'},
 {'slug':'rai-scuola-italiano','title':'Rai Scuola – Italiano','platform_id':P['rai-scuola-italiano'],'description':'محتوى تعليمي إيطالي من Rai Scuola يشمل اللغة والثقافة والمواد التعليمية المتاحة عبر المنصة.','category':'Italian','level':'Beginner–Advanced','language':'Italian','duration':'Self-paced','free':1,'certificate_available':0,'official_url':'https://www.raiscuola.rai.it/italiano'},
 {'slug':'pushkin-russian-online','title':'Pushkin Institute – Russian Language Resources','platform_id':P['pushkin-russian'],'description':'موارد ودورات رسمية من معهد بوشكين لتعلم الروسية، مع مستويات ومسارات رقمية. تحقق من كل دورة لمعرفة نوع الشهادة وشروطها.','category':'Russian','level':'A1–C1','language':'Russian / English','duration':'Self-paced / varies','free':1,'certificate_available':1,'certificate_type':'Certificate availability varies by course','official_url':'https://pushkininstitute.ru/learn'},
 {'slug':'sejong-korean-self-study','title':'Online King Sejong Institute – Korean Self-study','platform_id':P['sejong-korean'],'description':'منصة Online King Sejong Institute الرسمية لتعلم الكورية ذاتيًا وبمسارات منظمة من المبتدئ إلى المستويات الأعلى، مع معلومات رسمية عن الشهادة حسب المسار.','category':'Korean','level':'Beginner–Advanced','language':'Korean / English','duration':'Self-paced','free':1,'certificate_available':1,'certificate_type':'Certificate information provided by Online KSI; varies by course','official_url':'https://www.iksi.or.kr/lms/main/main.do'},
 {'slug':'chineseplus-hsk-standard-1','title':'ChinesePlus – HSK Standard Course Level 1','platform_id':P['chineseplus'],'description':'مقرر صيني للمبتدئين مبني على HSK Standard Course، ويغطي المهارات الأساسية في الاستماع والكلام والقراءة والكتابة.','category':'Chinese','level':'Beginner / HSK 1','language':'Chinese / English','duration':'Self-paced','free':1,'certificate_available':0,'official_url':'https://www.chineseplus.net/en/learning'},
 {'slug':'rug-free-introduction-dutch-mooc','title':'University of Groningen – Free Introduction to Dutch MOOC','platform_id':P['rug-language-centre'],'description':'MOOC مجاني لمدة ثلاثة أسابيع للتعرف على اللغة الهولندية والثقافة ومدينة Groningen، كما تصف الصفحة الرسمية.','category':'Dutch','level':'Beginner','language':'Dutch / English','duration':'3 weeks','free':1,'certificate_available':0,'official_url':'https://www.rug.nl/language-centre/language-courses/dutch/'},
 {'slug':'navoica-polish-language-mooc','title':'NAVOICA – Polish Language MOOC','platform_id':P['navoica-polish-plus'],'description':'دورات MOOCs بولندية على NAVOICA. يختلف وجود شهادة الإتمام حسب الدورة وشروطها.','category':'Polish','level':'Beginner–Advanced','language':'Polish','duration':'Varies','free':1,'certificate_available':1,'certificate_type':'Course-dependent completion certificate','official_url':'https://navoica.pl'},
 # citizen science / volunteer credentials
 {'slug':'zooniverse-volunteer-certificate','title':'Zooniverse – Citizen Science Volunteering','platform_id':P['zooniverse'],'description':'تطوع علمي رقمي: صنّف بيانات مشاريع بحثية وسجّل مساهماتك. Zooniverse يوفر شهادة تطوع رسمية يمكن توليدها من سجل المساهمات؛ من هم دون 16 يحتاجون موافقة ولي الأمر للتسجيل.','category':'Citizen Science / Volunteering','level':'All Ages','language':'Multiple','duration':'Flexible','free':1,'certificate_available':1,'certificate_type':'Official Zooniverse Volunteer Certificate','official_url':'https://www.zooniverse.org/get-involved/volunteer'},
 {'slug':'nasa-citizen-science-projects','title':'NASA Citizen Science Projects','platform_id':P['nasa-citizen-science'],'description':'مشاريع علم مواطن من NASA تتيح للناس من مختلف الأعمار المساهمة في أبحاث حقيقية؛ العمر ليس عائقًا عامًا لكن كل مشروع قد يضع شروطًا خاصة.','category':'NASA / Citizen Science','level':'All Ages','language':'English / Multiple','duration':'Varies','free':1,'certificate_available':0,'official_url':'https://science.nasa.gov/citizen-science/'},
 {'slug':'unicef-agora-free-learning','title':'UNICEF Agora – Free Learning','platform_id':P['unicef-agora'],'description':'تعلم مجاني ومفتوح للعامة في موضوعات UNICEF والعمل الإنساني والتنمية. معظم الأنشطة تتضمن تتبع الإكمال أو التقييم وقد تمنح شارات رقمية أو شهادات إتمام.','category':'Humanitarian / Development','level':'Beginner–Advanced','language':'Multiple','duration':'Varies','free':1,'certificate_available':1,'certificate_type':'Digital badge or certificate of completion when offered by the activity','official_url':'https://agora.unicef.org/'},
]
added=0
for c in courses:
 if c.get('platform_id'):
  added += add_course(c)

# Add a few non-duplicative opportunity records focused on training/volunteering and youth eligibility.
opps=[
 {'slug':'training-forage-deloitte-data-analytics','type':'training','title':'Deloitte Australia – Data Analytics Virtual Experience','organization':'Forage / Deloitte','description':'تجربة مهنية افتراضية مجانية تحاكي مهام محلل بيانات لدى Deloitte. مناسبة للاستكشاف المهني، وتصدر شهادة إتمام عند إنهاء البرنامج. تحقق من صفحة البرنامج للعمر والمتطلبات الحالية قبل التسجيل.','country':'Global / Online','online':1,'age_min':16,'age_max':25,'education_level':'Secondary / University','category':'Training / Data Analytics','language':'English','funding_type':'Free','tuition_covered':1,'certificate':1,'duration':'Self-paced','application_url':'https://www.theforage.com/simulations/deloitte-au/data-analytics-3rjz','official_source':'https://www.theforage.com/simulations','source_type':'official','verified':1,'status':'open','last_checked':TODAY,'eligibility':'تحقق من العمر وشروط البرنامج في صفحة Forage قبل البدء.','requirements':'إنشاء حساب وإكمال المهام المطلوبة.','about_opportunity':'تجربة محاكاة وليست وظيفة مدفوعة ولا تدريبًا ميدانيًا.','keywords':'Forage,Deloitte,data analytics,training,virtual experience'},
 {'slug':'volunteer-zooniverse-under16','type':'volunteer','title':'Zooniverse – Online Citizen Science Volunteering','organization':'Zooniverse','description':'تطوع علمي أونلاين يساعد باحثين في تصنيف وتحليل بيانات مشاريع حقيقية. يمكن توليد شهادة تطوع رسمية من سجل المساهمات؛ من هم دون 16 يحتاجون موافقة ولي الأمر للتسجيل.','country':'Global / Online','online':1,'age_min':0,'age_max':17,'education_level':'All','category':'Volunteering / Citizen Science','language':'Multiple','funding_type':'Free','tuition_covered':1,'certificate':1,'duration':'Flexible','application_url':'https://www.zooniverse.org/get-involved/volunteer','official_source':'https://www.zooniverse.org/get-involved/volunteer','source_type':'official','verified':1,'status':'open','last_checked':TODAY,'eligibility':'جميع الأعمار يمكنها التطوع؛ من هم دون 16 يحتاجون موافقة ولي الأمر على التسجيل.','requirements':'حساب Zooniverse والالتزام بإرشادات المشروع.','about_opportunity':'تطوع علمي رقمي مرن وليس وظيفة مدفوعة.','keywords':'Zooniverse,volunteer,citizen science,under 18'},
 {'slug':'volunteer-nasa-citizen-science','type':'volunteer','title':'NASA Citizen Science – Open Projects','organization':'NASA','description':'مشاريع علم مواطن رسمية من NASA تسمح بالمشاركة في أبحاث حقيقية. NASA تقول إن الأشخاص من جميع الأعمار يمكنهم أن يكونوا علماء مواطنين، مع اختلاف متطلبات كل مشروع.','country':'Global / Online','online':1,'age_min':0,'age_max':None,'education_level':'All','category':'Volunteering / Science','language':'English / Multiple','funding_type':'Free','tuition_covered':1,'certificate':0,'duration':'Varies','application_url':'https://science.nasa.gov/citizen-science/','official_source':'https://science.nasa.gov/get-involved/citizen-science/how-to-contribute-to-citizen-science-with-nasa/','source_type':'official','verified':1,'status':'open','last_checked':TODAY,'eligibility':'العمر ليس عائقًا عامًا، لكن تحقق من شروط المشروع المحدد.','requirements':'حساب/أدوات تختلف حسب المشروع.','about_opportunity':'مشاركة تطوعية في أبحاث NASA وليست تدريبًا وظيفيًا.','keywords':'NASA,citizen science,volunteer,science,under 18'},
]
for o in opps: add_opp(o)

conn.commit()
print('added courses',added,'platforms',conn.execute("select count(*) from platforms").fetchone()[0],'courses',conn.execute("select count(*) from courses").fetchone()[0],'opportunities',conn.execute("select count(*) from opportunities").fetchone()[0])
conn.close()
