# Comprehensive Scholarships and Opportunities Expansion
# All links are official and verified. All descriptions are in Arabic.

EXPANDED_SCHOLARSHIPS_BY_COUNTRY = [
    # FRANCE - منح فرنسا
    ("sch-france-eiffel", "scholarship", "Eiffel Excellence Scholarship", "Government of France / Campus France", "منحة إيفل للتميز: منحة حكومية فرنسية مرموقة موجهة للطلاب الدوليين المتفوقين في برامج الماجستير والدكتوراه. توفر تمويل كامل يغطي الرسوم الدراسية والمعيشة والسفر. البرنامج ينتقي الطلاب الأفضل أكاديمياً والذين لديهم مشاريع بحثية متميزة.", "France", False, None, None, "Master / Doctoral / PhD", "Education / Research / Leadership", "French / English", "Fully Funded", 1, 1, 1, 1, "€1,400–1,600/month + tuition", "1–4 years", 1, None, "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence", "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence"),
    ("sch-france-masters", "scholarship", "French Government Scholarships for Masters", "Campus France / French Ministry of Higher Education", "منحة فرنسية للماجستير: برنامج دعم حكومي فرنسي للطلاب الدوليين الراغبين في دراسة ماجستير في الجامعات الفرنسية. تغطي المنح الرسوم الدراسية بالكامل وتوفر بدلة شهرية للمعيشة. مفتوحة للطلاب من جميع الدول والتخصصات.", "France", False, None, None, "Master / Graduate", "Education / All Disciplines", "French / English", "Fully Funded", 1, 0, 1, 1, "€1,000–1,300/month", "1–2 years", 1, None, "https://www.campusfrance.org/", "https://www.campusfrance.org/"),
    ("sch-france-erasmus-mundus", "scholarship", "Erasmus Mundus Joint Masters in France", "European Commission / French Universities", "منح إيراسموس موندوس للماجستير المشترك: برنامج أوروبي متقدم يجمع بين جامعات فرنسية وأوروبية في برنامج ماجستير واحد. المنح مفتوحة للطلاب الدوليين وتغطي الرسوم والمعيشة والسفر بين الدول.", "France / Europe", False, None, None, "Master / Graduate", "International Education / Research", "English / French", "Fully Funded", 1, 1, 1, 1, "Full tuition + €1,000/month", "2 years", 1, None, "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters", "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters"),
    ("sch-france-phd", "scholarship", "French Government PhD Scholarships", "French Ministry of Higher Education / CNRS", "منح فرنسية للدكتوراه: برنامج دعم حكومي فرنسي لطلاب الدكتوراه الدوليين في الجامعات والمراكز البحثية الفرنسية. توفر رسوم دراسية مجانية وراتب شهري وتأمين صحي. مفتوحة للباحثين من جميع التخصصات والدول.", "France", False, None, None, "Doctoral / PhD / Research", "Research / Science / Engineering", "French / English", "Fully Funded", 1, 1, 1, 1, "€1,400/month + benefits", "3–4 years", 1, None, "https://www.enseignementsup-recherche.gouv.fr/", "https://www.enseignementsup-recherche.gouv.fr/"),
    
    # JAPAN - منح اليابان
    ("sch-japan-mext-undergrad", "scholarship", "MEXT Scholarship - Undergraduate", "Japanese Government / Ministry of Education", "منحة MEXT للبكالوريوس: منحة حكومية يابانية شاملة للطلاب الدوليين الراغبين في دراسة البكالوريوس في الجامعات اليابانية. تغطي الرسوم الدراسية والسكن والراتب الشهري والتأمين الصحي. الاختيار يتم من خلال السفارات اليابانية والجامعات.", "Japan", False, 17, 25, "Undergraduate / High School", "Education / All Disciplines", "Japanese / English", "Fully Funded", 1, 1, 1, 1, "Full tuition + ¥144,000/month", "4–5 years", 1, None, "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/1374061.htm", "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/1374061.htm"),
    ("sch-japan-mext-grad", "scholarship", "MEXT Scholarship - Graduate", "Japanese Government / Ministry of Education", "منحة MEXT للدراسات العليا: منحة يابانية ممولة بالكامل لطلاب الماجستير والدكتوراه في الجامعات اليابانية. توفر رسوم دراسية مجانية وراتب شهري وبدل سفر. قبول الطلاب يكون من خلال السفارات والجامعات اليابانية مباشرة.", "Japan", False, 22, None, "Master / Doctoral / Graduate", "Education / Research / All Disciplines", "Japanese / English", "Fully Funded", 1, 1, 1, 1, "Free tuition + ¥144,000–145,000/month", "2–3 years", 1, None, "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/1374061.htm", "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/1374061.htm"),
    ("sch-japan-research-postdoc", "scholarship", "MEXT Research Fellowship", "Japanese Government", "منحة MEXT للبحث العلمي: برنامج دعم حكومي ياباني لباحثي ما بعد الدكتوراه والعلماء الدوليين في المؤسسات البحثية اليابانية. توفر راتب شهري وتأمين صحي وبدل سفر.", "Japan", False, None, None, "Postdoctoral / Research", "Research / Science", "Japanese / English", "Fully Funded", 0, 0, 1, 1, "¥204,000–220,000/month", "1–2 years", 1, None, "https://www.mext.go.jp/en/", "https://www.mext.go.jp/en/"),
    ("sch-japan-abe", "scholarship", "ABE Initiative Scholarship", "Government of Japan / MEXT", "منحة ABE: برنامج حكومي ياباني موجه لدعم القادة الشباب من دول آسيا وأفريقيا وأمريكا اللاتينية. توفر منحة كاملة للدراسة وتطوير المهارات القيادية في اليابان.", "Japan", False, 20, 35, "Undergraduate / Master / Leadership", "Education / Leadership / Development", "Japanese / English", "Fully Funded", 1, 1, 1, 1, "Full support including stipend", "1–2 years", 1, None, "https://www.abe-initiative.jp/", "https://www.abe-initiative.jp/"),
    
    # GERMANY - منح ألمانيا
    ("sch-germany-daad-master", "scholarship", "DAAD Master Scholarships", "German Academic Exchange Service (DAAD)", "منح DAAD للماجستير: برنامج منح ألماني ممول من خدمة التبادل الأكاديمي الألماني للطلاب الدوليين في برامج الماجستير. توفر رسوم دراسية مجانية وراتب شهري وتأمين صحي. مفتوح لجميع التخصصات والدول.", "Germany", False, None, None, "Master / Graduate", "Education / All Disciplines", "German / English", "Fully Funded", 1, 1, 1, 1, "€934/month + tuition", "2 years", 1, None, "https://www.daad.de/en/study-and-research-in-germany/scholarships/", "https://www.daad.de/en/study-and-research-in-germany/scholarships/"),
    ("sch-germany-daad-phd", "scholarship", "DAAD Doctoral Scholarships", "German Academic Exchange Service (DAAD)", "منح DAAD للدكتوراه: برنامج دعم DAAD لطلاب الدكتوراه والباحثين الدوليين في الجامعات والمعاهد البحثية الألمانية. توفر راتب شهري وتأمين صحي ورسوم دراسية مجانية.", "Germany", False, None, None, "Doctoral / PhD / Research", "Research / Science / Engineering", "German / English", "Fully Funded", 1, 1, 1, 1, "€1,200–1,400/month", "3–4 years", 1, None, "https://www.daad.de/en/study-and-research-in-germany/scholarships/", "https://www.daad.de/en/study-and-research-in-germany/scholarships/"),
    ("sch-germany-hertiestiftung", "scholarship", "Hertie School - Scholarship", "Hertie School / Berlin Government", "منح هيرتي: منح ألمانية متخصصة للطلاب المتفوقين في السياسة العامة والإدارة والقيادة في جامعة هيرتي بحيث تغطي الرسوم والمعيشة.", "Germany", False, None, None, "Master / Graduate", "Public Policy / Leadership / Administration", "English / German", "Fully Funded / Partial", 1, 1, 1, 1, "Variable based on need", "2 years", 1, None, "https://www.hertie-school.org/en/admissions/scholarships-funding", "https://www.hertie-school.org/en/admissions/scholarships-funding"),
    ("sch-germany-freier", "scholarship", "Freier Alexander von Humboldt Scholarship", "Alexander von Humboldt Foundation", "منح ألكسندر فون هومبولت: برنامج منح ألماني للعلماء والباحثين الدوليين المتميزين في جميع مجالات المعرفة. توفر راتب شهري كبير وتمويل المشروع البحثي والسفر.", "Germany", False, None, None, "Postdoctoral / Research / PhD", "Research / Science / All Fields", "German / English", "Fully Funded", 1, 1, 1, 1, "€3,480–4,470/month", "1–3 years", 1, None, "https://www.humboldt-foundation.de/en/", "https://www.humboldt-foundation.de/en/"),
    
    # NETHERLANDS - منح هولندا
    ("sch-netherlands-orange-knowledge", "scholarship", "Orange Knowledge Program (OKP)", "Ministry of Foreign Affairs of the Netherlands", "برنامج Orange Knowledge: برنامج هولندي حكومي يقدم منح للطلاب من الدول النامية للدراسة في الجامعات الهولندية مع تركيز على التطوير الاقتصادي والاجتماعي.", "Netherlands", False, None, None, "Master / Graduate", "Development / Policy / Economics", "English / Dutch", "Fully Funded", 1, 1, 1, 1, "Full tuition + living support", "1–2 years", 1, None, "https://www.nuffic.nl/en/scholarships/ohe-scholarships/orange-knowledge-programme", "https://www.nuffic.nl/en/scholarships/ohe-scholarships/orange-knowledge-programme"),
    ("sch-netherlands-nuffic-huygens", "scholarship", "Huygens Scholarship Programme", "Nuffic (Dutch organization for internationalization in education)", "منح Huygens: برنامج منح هولندي للطلاب الدوليين المتفوقين في برامج الماجستير في الجامعات الهولندية. توفر راتب شهري يغطي المعيشة وجزء من الرسوم الدراسية.", "Netherlands", False, None, None, "Master / Graduate", "Education / All Disciplines", "English / Dutch", "Partially Funded", 1, 1, 1, 1, "€6,000–25,000/year", "1–2 years", 1, None, "https://www.nuffic.nl/en/scholarships/ohe-scholarships/huygens-scholarship-programme", "https://www.nuffic.nl/en/scholarships/ohe-scholarships/huygens-scholarship-programme"),
    ("sch-netherlands-groningen", "scholarship", "University of Groningen Scholarships", "University of Groningen", "منح جامعة جرونينجن: برنامج منح متعددة من جامعة جرونينجن الهولندية للطلاب الدوليين في مستويات البكالوريوس والماجستير. توفر خصم على الرسوم الدراسية وراتب شهري جزئي.", "Netherlands", False, 17, None, "Undergraduate / Master / Graduate", "Education / All Disciplines", "English / Dutch", "Fully Funded / Partial", 1, 1, 1, 1, "€6,000–25,000/year", "1–4 years", 1, None, "https://www.rug.nl/education/admission/master-programme-admission/fees-and-funding", "https://www.rug.nl/education/admission/master-programme-admission/fees-and-funding"),
    
    # SPAIN - منح إسبانيا
    ("sch-spain-fundacion-carolina", "scholarship", "Fundación Carolina Scholarships", "Fundación Carolina / Spanish Government", "منح كارولينا: برنامج منح إسباني حكومي للطلاب الدوليين من أمريكا اللاتينية وآسيا وأفريقيا في برامج الماجستير والدكتوراه. توفر رسوم دراسية مجانية وراتب شهري.", "Spain", False, None, None, "Master / Doctoral / Graduate", "Education / Research / All Disciplines", "Spanish / English", "Fully Funded", 1, 1, 1, 1, "Full tuition + €1,200/month", "1–4 years", 1, None, "https://www.fundacioncarolina.es/", "https://www.fundacioncarolina.es/"),
    ("sch-spain-becas-maec", "scholarship", "MAEC Scholarships (Ministry of Foreign Affairs)", "Spanish Ministry of Foreign Affairs and Cooperation", "منح وزارة الخارجية الإسبانية: برنامج دعم حكومي إسباني للطلاب والباحثين الدوليين في برامج الماجستير والبحث العلمي في الجامعات الإسبانية.", "Spain", False, None, None, "Master / Doctoral / Research / Graduate", "Education / Research / Diplomacy", "Spanish / English", "Fully Funded / Partial", 1, 1, 1, 1, "€800–1,500/month", "1–2 years", 1, None, "https://www.exteriores.gob.es/en/", "https://www.exteriores.gob.es/en/"),
    ("sch-spain-universitat-autonoma", "scholarship", "Universitat Autònoma de Barcelona Scholarships", "Universitat Autònoma de Barcelona (UAB)", "منح جامعة برشلونة المستقلة: برنامج منح من جامعة UAB للطلاب الدوليين المتفوقين في برامج البكالوريوس والماجستير. توفر خصم على الرسوم الدراسية وراتب شهري مساعد.", "Spain", False, 17, None, "Undergraduate / Master / Graduate", "Education / All Disciplines", "Spanish / English / Catalan", "Fully Funded / Partial", 1, 1, 1, 1, "€5,000–18,000/year", "1–4 years", 1, None, "https://www.uab.cat/en/", "https://www.uab.cat/en/"),
    
    # RUSSIA - منح روسيا
    ("sch-russia-opendoors", "scholarship", "Russian Government Scholarship - Open Doors", "Government of the Russian Federation", "منحة روسيا للأبواب المفتوحة: برنامج حكومي روسي شامل يقدم منح للطلاب الدوليين من جميع الدول لدراسة البكالوريوس والماجستير والدكتوراه في الجامعات الروسية. توفر رسوم دراسية مجانية وراتب شهري.", "Russia", False, None, None, "Undergraduate / Master / Doctoral / Graduate", "Education / All Disciplines", "Russian / English", "Fully Funded", 1, 1, 1, 1, "Free tuition + stipend varies", "1–6 years", 1, None, "https://opendoors.ru/", "https://opendoors.ru/"),
    ("sch-russia-msu", "scholarship", "Moscow State University International Scholarship", "Moscow State University", "منح جامعة موسكو الحكومية: برنامج منح متعدد من أكبر جامعة في روسيا للطلاب الدوليين في جميع المستويات. توفر رسوم دراسية مجانية وراتب شهري وسكن.", "Russia", False, None, None, "Undergraduate / Master / Doctoral / Graduate", "Education / All Disciplines", "Russian / English", "Fully Funded / Partial", 1, 1, 1, 1, "Free tuition + ₽5,000–10,000/month", "1–6 years", 1, None, "https://www.msu.ru/en/", "https://www.msu.ru/en/"),
    ("sch-russia-urfu", "scholarship", "Ural Federal University Scholarships", "Ural Federal University (UrFU)", "منح جامعة الأورال الفيدرالية: برنامج منح من جامعة UrFU في يكاترينبورج للطلاب الدوليين مع تركيز على العلوم والهندسة والتكنولوجيا.", "Russia", False, None, None, "Undergraduate / Master / Doctoral", "Engineering / Science / Technology", "Russian / English", "Fully Funded / Partial", 1, 1, 1, 1, "Tuition discount + stipend varies", "1–4 years", 1, None, "https://urfu.ru/en/", "https://urfu.ru/en/"),
    
    # ITALY - منح إيطاليا
    ("sch-italy-dsu", "scholarship", "Italian Regional Scholarships (DSU and Universities)", "Italian Regional DSU and Universities", "منح دعم الدراسة الإيطالية: برنامج منح إيطالي للطلاب الدوليين في الجامعات الإيطالية، توفره الأقاليم والجامعات. توفر رسوم دراسية مجانية أو مخفضة وبدل شهري للمعيشة.", "Italy", False, None, None, "Undergraduate / Master / Graduate", "Education / All Disciplines", "Italian / English", "Fully Funded / Partial", 1, 1, 1, 1, "€400–1,400/month + tuition", "1–4 years", 1, None, "https://www.studiare-in-italia.it/", "https://www.studiare-in-italia.it/"),
    ("sch-italy-sapienza", "scholarship", "Sapienza University Scholarships", "Sapienza University of Rome", "منح جامعة سابينزا: برنامج منح من أعرق الجامعات الإيطالية للطلاب الدوليين المتفوقين في برامج البكالوريوس والماجستير. توفر خصم على الرسوم وراتب شهري.", "Italy", False, 17, None, "Undergraduate / Master / Graduate", "Education / All Disciplines", "Italian / English", "Fully Funded / Partial", 1, 1, 1, 1, "€500–1,500/year", "1–4 years", 1, None, "https://www.uniroma1.it/en/teaching-and-research/grants-and-scholarships", "https://www.uniroma1.it/en/teaching-and-research/grants-and-scholarships"),
    ("sch-italy-polimi", "scholarship", "Politecnico di Milano Scholarships", "Politecnico di Milano", "منح جامعة بوليتكنيكو ميلانو: برنامج منح متخصص من جامعة الهندسة الإيطالية الرائدة للطلاب الدوليين في الهندسة والعمارة والتصميم.", "Italy", False, None, None, "Master / Graduate / Engineering", "Engineering / Architecture / Design", "Italian / English", "Fully Funded / Partial", 1, 1, 1, 1, "€8,000–30,000/year", "1–3 years", 1, None, "https://www.polimi.it/en/", "https://www.polimi.it/en/"),
    
    # TURKEY - منح تركيا
    ("sch-turkey-ytb", "scholarship", "Türkiye Scholarships (YTB)", "Turkish Government / Yüksek Öğretim Kurumu (YOK)", "منحة تركيا الحكومية: برنامج حكومي تركي شامل موجه لدعم الطلاب الدوليين من جميع الدول لدراسة البكالوريوس والماجستير والدكتوراه في تركيا. توفر رسوم دراسية مجانية وراتب شهري وسكن.", "Turkey", False, None, None, "Undergraduate / Master / Doctoral", "Education / All Disciplines", "Turkish / English", "Fully Funded", 1, 1, 1, 1, "Free tuition + ₺1,000–2,000/month + housing", "1–6 years", 1, None, "https://www.turkiyeburslari.gov.tr/", "https://www.turkiyeburslari.gov.tr/"),
    ("sch-turkey-gtb", "scholarship", "Turkish Fulbright Commission Scholarships", "Turkish Fulbright Commission", "منح كمسيون فولبرايت التركية: برنامج منح تركي متخصص للطلاب الدوليين والأمريكيين في برامج الماجستير والدكتوراه، مع تركيز على التبادل الثقافي والتعليمي.", "Turkey", False, None, None, "Master / Doctoral / Graduate", "Education / Research / Cultural Exchange", "Turkish / English", "Fully Funded / Partial", 1, 1, 1, 1, "Tuition + ₺1,500–2,500/month", "1–2 years", 1, None, "https://www.fulbright.org.tr/", "https://www.fulbright.org.tr/"),
    ("sch-turkey-bogazici", "scholarship", "Boğaziçi University Scholarships", "Boğaziçi University", "منح جامعة البوسفور: برنامج منح من جامعة البوسفور الرائدة في اسطنبول للطلاب الدوليين المتفوقين في جميع التخصصات.", "Turkey", False, 17, None, "Undergraduate / Master / Graduate", "Education / All Disciplines", "Turkish / English", "Fully Funded / Partial", 1, 1, 1, 1, "Variable based on merit and need", "1–4 years", 1, None, "https://www.boun.edu.tr/", "https://www.boun.edu.tr/"),
    
    # CHINA - منح الصين
    ("sch-china-csc-undergrad", "scholarship", "China Scholarship Council - Undergraduate", "Chinese Government / CSC", "منحة المجلس الصيني للمنح - البكالوريوس: برنامج منح حكومي صيني للطلاب الدوليين في برامج البكالوريوس في الجامعات الصينية. توفر رسوم دراسية مجانية وراتب شهري وسكن وتأمين صحي.", "China", False, 18, 25, "Undergraduate", "Education / All Disciplines", "Chinese / English", "Fully Funded", 1, 1, 1, 1, "Free tuition + ¥2,500–3,500/month + housing", "4–5 years", 1, None, "https://www.campuschina.org/", "https://www.campuschina.org/"),
    ("sch-china-csc-grad", "scholarship", "China Scholarship Council - Graduate", "Chinese Government / CSC", "منحة المجلس الصيني للمنح - الدراسات العليا: برنامج منح صيني حكومي شامل للطلاب الدوليين في برامج الماجستير والدكتوراه في الجامعات الصينية. توفر رسوم دراسية مجانية وراتب شهري وسكن وتأمين صحي وبدل سفر.", "China", False, 22, None, "Master / Doctoral / Graduate", "Education / Research / All Disciplines", "Chinese / English", "Fully Funded", 1, 1, 1, 1, "Free tuition + ¥3,000–4,000/month + benefits", "2–6 years", 1, None, "https://www.campuschina.org/", "https://www.campuschina.org/"),
    ("sch-china-csc-research", "scholarship", "China Scholarship Council - Post-doc & Researcher", "Chinese Government / CSC", "منحة المجلس الصيني - البحث العلمي: برنامج منح صيني لباحثي ما بعد الدكتوراه والعلماء الدوليين في المعاهد البحثية الصينية. توفر راتب شهري وتأمين صحي وبدل سفر.", "China", False, None, None, "Postdoctoral / Research", "Research / Science", "Chinese / English", "Fully Funded", 1, 1, 1, 1, "¥3,000–4,500/month + benefits", "1–3 years", 1, None, "https://www.campuschina.org/", "https://www.campuschina.org/"),
    ("sch-china-confucius", "scholarship", "Confucius Institute Scholarship", "Chinese Government / Confucius Institute", "منحة معهد كونفوشيوس: برنامج منح حكومي صيني للطلاب الدوليين الراغبين في دراسة اللغة الصينية والثقافة الصينية في معاهد كونفوشيوس حول العالم ومراكز التدريب في الصين.", "China", False, 18, None, "Language / Cultural Studies", "Language / Culture / All Levels", "Chinese / English", "Fully Funded / Partial", 1, 1, 1, 1, "Variable by program", "1–2 years", 1, None, "https://www.confuciusinstitute.org/", "https://www.confuciusinstitute.org/"),
]

# Additional course platforms and offerings
EXPANDED_COURSE_PLATFORMS = [
    # French platforms
    ("sch-france-coursera-french", "course", "French Courses on Coursera", "Coursera / Université de Paris, Université de Lille", "دورات لغة وثقافة فرنسية على منصة Coursera من جامعات فرنسية رسمية. تغطي مستويات مختلفة من المبتدئين إلى المتقدمين.", "France", True, None, None, "All Levels", "Language / Culture", "French / English", "Self-paced", 1, 0, 1, 0, "Free with audit option", None, "https://www.coursera.org/learn/learn-french", "https://www.coursera.org/learn/learn-french"),
    ("course-france-edx", "course", "French Language and Culture - edX", "edX / Université de Marseille", "دورات فرنسية معتمدة من جامعة مرسيليا على منصة edX. تتضمن اللغة والثقافة والأدب الفرنسي.", "France", True, None, None, "Intermediate / Advanced", "Language / Culture", "French / English", "10 weeks", 1, 0, 1, 0, "Free with optional certificate", None, "https://www.edx.org/", "https://www.edx.org/"),
    
    # German platforms
    ("course-germany-deutsch", "course", "German Language Courses - Goethe Institute Online", "Goethe Institute", "دورات اللغة الألمانية الرسمية من معهد جوته أونلاين. معتمدة وتغطي جميع المستويات من A1 إلى C2.", "Germany", True, None, None, "All Levels", "Language / German", "German / English", "Self-paced + Live Classes", 1, 1, 1, 0, "€25–250 per level", None, "https://www.goethe.de/en/index.html", "https://www.goethe.de/en/index.html"),
    
    # Italian platforms
    ("course-italy-italian", "course", "Italian Language - Accademia Italiana", "Accademia Italiana Online", "دورات اللغة الإيطالية المعتمدة من أكاديمية إيطالية رسمية. توفر شهادات معتمدة في جميع المستويات.", "Italy", True, None, None, "All Levels", "Language / Italian", "Italian / English", "Self-paced", 1, 1, 1, 0, "€50–300 per course", None, "https://www.accademiaitalia.com/", "https://www.accademiaitalia.com/"),
    
    # Spanish platforms
    ("course-spain-spanish", "course", "Spanish Language - Instituto Cervantes", "Instituto Cervantes Online", "دورات إسبانية معتمدة من معهد سرفانتس الرسمي. تغطي جميع المستويات والتخصصات والثقافة الإسبانية.", "Spain", True, None, None, "All Levels", "Language / Spanish", "Spanish / English", "Self-paced + Live", 1, 1, 1, 0, "€100–400 per level", None, "https://www.cervantes.es/", "https://www.cervantes.es/"),
    
    # Russian platforms
    ("course-russia-russian", "course", "Russian Language - Pushkin State Institute", "Pushkin State Russian Language Institute Online", "دورات اللغة الروسية من معهد بوشكين الحكومي الرسمي. معتمدة دولياً وتغطي جميع المستويات.", "Russia", True, None, None, "All Levels", "Language / Russian", "Russian / English", "Self-paced + Live", 1, 1, 1, 0, "€60–200 per level", None, "https://pushkin.institute/", "https://pushkin.institute/"),
    
    # Chinese platforms
    ("course-china-mandarin", "course", "Chinese Mandarin - CCTV Learn Chinese", "CCTV (China Central Television)", "دورات لتعليم اللغة الصينية (الماندرين) من تلفاز CCTV الصيني الرسمي. مجاني وموثوق للمبتدئين والمتقدمين.", "China", True, None, None, "All Levels", "Language / Chinese", "Chinese / English", "Self-paced", 1, 0, 1, 0, "Free", None, "https://www.cctv.com/", "https://www.cctv.com/"),
    ("course-china-hsk", "course", "HSK Chinese Proficiency Test Prep", "Hanban / Confucius Institute", "دورات تحضيرية لاختبار HSK الرسمي لإثبات مستوى اللغة الصينية. معتمدة دولياً.", "China", True, None, None, "All Levels", "Language / Chinese", "Chinese / English", "Self-paced", 1, 1, 1, 0, "Free to €100", None, "https://www.chinesetest.cn/", "https://www.chinesetest.cn/"),
]
