# Official-source additions for ZAAD. Existing catalog is preserved; these rows are additive.
SUPPLEMENTAL_PLATFORMS = [
    {
        "slug": "goethe-institut", "name": "Goethe-Institut",
        "description": "الجهة الثقافية الرسمية لألمانيا وتوفر مسارات ودورات لتعلم الألمانية أونلاين وحضوريًا بمستويات A1–C2.",
        "official_url": "https://www.goethe.de/", "courses_url": "https://www.goethe.de/en/spr/kur/typ.html",
        "country": "Germany / Global", "categories": ["German", "Languages", "Culture"],
        "free_courses_available": 1, "certificates_available": 1,
        "free_access_guide": "توجد مواد تدريبية واختبار تحديد مستوى وممارسة مجانية؛ الدورات المنظمة والاختبارات الرسمية مدفوعة حسب العرض.",
        "official_source": "https://www.goethe.de/"
    },
    {
        "slug": "institut-francais", "name": "Institut français",
        "description": "شبكة المعاهد الفرنسية التابعة لوزارة أوروبا والشؤون الخارجية الفرنسية وتوفر برامج وموارد لتعلم الفرنسية والثقافة الفرنسية.",
        "official_url": "https://www.institutfrancais.com/", "courses_url": "https://www.institutfrancais.com/",
        "country": "France / Global", "categories": ["French", "Languages", "Culture"],
        "free_courses_available": 0, "certificates_available": 1,
        "free_access_guide": "توفر بعض الفروع والبرامج موارد وأنشطة مجانية؛ الأسعار والمواعيد تختلف حسب المعهد المحلي.",
        "official_source": "https://www.institutfrancais.com/"
    },
    {
        "slug": "japan-foundation-irodori", "name": "The Japan Foundation – IRODORI",
        "description": "مورد رسمي من مؤسسة اليابان لتعلم اليابانية للحياة اليومية والعمل، مع مواد دراسية رقمية مجانية.",
        "official_url": "https://www.jpf.go.jp/e/", "courses_url": "https://www.irodori.jpf.go.jp/en/",
        "country": "Japan / Global", "categories": ["Japanese", "Languages", "Culture"],
        "free_courses_available": 1, "certificates_available": 0,
        "free_access_guide": "افتح IRODORI واستخدم مواد المستويات المتاحة مجانًا، ثم راجع اختبارات JLPT أو برامج اليابان الرسمية إذا احتجت اعتمادًا.",
        "official_source": "https://www.irodori.jpf.go.jp/en/"
    },
    {
        "slug": "instituto-cervantes", "name": "Instituto Cervantes",
        "description": "المؤسسة الإسبانية الرسمية المتخصصة في نشر اللغة والثقافة الإسبانية، وتقدم دورات واختبارات وموارد تعلم.",
        "official_url": "https://cervantes.org/", "courses_url": "https://cervantes.org/",
        "country": "Spain / Global", "categories": ["Spanish", "Languages", "Culture"],
        "free_courses_available": 0, "certificates_available": 1,
        "free_access_guide": "توجد موارد مجانية على بعض مواقع المعاهد، بينما الدورات المنظمة واختبارات DELE/SIELE تخضع لرسوم حسب المركز.",
        "official_source": "https://cervantes.org/"
    },
    {
        "slug": "yunus-emre-institute", "name": "Yunus Emre Institute",
        "description": "المؤسسة التركية الثقافية الرسمية التي تدعم تعلم اللغة التركية والثقافة التركية عبر مراكز وبرامج دولية.",
        "official_url": "https://www.yee.org.tr/en", "courses_url": "https://turkce.yee.org.tr/",
        "country": "Türkiye / Global", "categories": ["Turkish", "Languages", "Culture"],
        "free_courses_available": 1, "certificates_available": 1,
        "free_access_guide": "استخدم موارد Türkçe التابعة لمعهد يونس إمره، وتحقق من المركز أو البرنامج لمعرفة ما إذا كان التسجيل والاختبار مجانيين.",
        "official_source": "https://turkce.yee.org.tr/"
    },
    {
        "slug": "pushkin-institute", "name": "Pushkin Institute",
        "description": "معهد روسي متخصص في اللغة والثقافة الروسية ويقدم موارد رقمية وبرامج لتعلم الروسية.",
        "official_url": "https://pushkininstitute.ru/", "courses_url": "https://pushkininstitute.ru/learn",
        "country": "Russia / Global", "categories": ["Russian", "Languages", "Culture"],
        "free_courses_available": 1, "certificates_available": 1,
        "free_access_guide": "ابدأ بالموارد والدروس الرقمية المتاحة على منصة المعهد، ثم تحقق من رسوم الاختبارات أو البرامج المنظمة.",
        "official_source": "https://pushkininstitute.ru/"
    },
    {
        "slug": "dante-alighieri", "name": "Società Dante Alighieri",
        "description": "مؤسسة ثقافية دولية تعزز اللغة والثقافة الإيطالية وتوفر دورات واختبارات عبر مراكزها وشبكتها الدولية.",
        "official_url": "https://www.dante.global/", "courses_url": "https://www.dante.global/",
        "country": "Italy / Global", "categories": ["Italian", "Languages", "Culture"],
        "free_courses_available": 0, "certificates_available": 1,
        "free_access_guide": "تختلف المواد والبرامج حسب المركز؛ افحص أقرب مركز رسمي لمعرفة الدورات المجانية أو المدفوعة.",
        "official_source": "https://www.dante.global/"
    },
    {
        "slug": "university-amsterdam-dutch", "name": "University of Amsterdam – Dutch Language",
        "description": "دورات رسمية للغة الهولندية عبر مركز اللغات بجامعة أمستردام، مع مستويات وبرامج تختلف حسب الفصل.",
        "official_url": "https://www.uva.nl/en", "courses_url": "https://www.uva.nl/en/education/other-programmes/language-courses/language-courses.html",
        "country": "Netherlands", "categories": ["Dutch", "Languages", "Academic"],
        "free_courses_available": 0, "certificates_available": 0,
        "free_access_guide": "الدورات المنظمة عادةً مدفوعة؛ استخدم صفحة المركز لمعرفة التسجيل والمواعيد والرسوم الحالية.",
        "official_source": "https://www.uva.nl/en/education/other-programmes/language-courses/language-courses.html"
    },
    {
        "slug": "chineseplus", "name": "Chinese Plus",
        "description": "منصة رقمية لتعلم الصينية توفر محتوى ومسارات لغوية عبر الإنترنت؛ تحقق من تفاصيل كل مسار من الموقع الرسمي.",
        "official_url": "https://www.chineseplus.net/", "courses_url": "https://www.chineseplus.net/",
        "country": "China / Global", "categories": ["Chinese", "Languages", "Culture"],
        "free_courses_available": 1, "certificates_available": 0,
        "free_access_guide": "افتح المسارات المتاحة على المنصة وتحقق من شروط الوصول لكل مادة قبل التسجيل.",
        "official_source": "https://www.chineseplus.net/"
    },
]

SUPPLEMENTAL_COURSES = [
    {"slug":"lang-fr-tv5","title":"Apprendre le français – TV5MONDE","platform":"institut-francais","description":"منصة تعلم فرنسية رقمية توفر أنشطة وفيديوهات وتمارين لمستويات متعددة، ويمكن استخدامها ذاتيًا.","category":"French","level":"A1–B2","language":"French","duration":"Self-paced","free":1,"certificate_available":0,"certificate_type":"","price":"Free","financial_aid":0,"official_url":"https://apprendre.tv5monde.com/"},
    {"slug":"lang-de-goethe-training","title":"German Online Training","platform":"goethe-institut","description":"تدريب ألماني ذاتي عبر الإنترنت من Goethe-Institut مع مواد لتطوير الاستماع والقراءة والمفردات عبر مستويات متعددة.","category":"German","level":"A1–C1","language":"German","duration":"Self-paced","free":0,"certificate_available":0,"certificate_type":"","price":"Paid; verify current offer","financial_aid":0,"official_url":"https://www.goethe.de/en/spr/kur/typ.html"},
    {"slug":"lang-ja-irodori","title":"IRODORI: Japanese for Life in Japan","platform":"japan-foundation-irodori","description":"مواد رسمية مجانية لتعلم اليابانية العملية للحياة اليومية والعمل، مع دروس ومواد قابلة للتنزيل.","category":"Japanese","level":"A1–B1","language":"Japanese / English","duration":"Self-paced","free":1,"certificate_available":0,"certificate_type":"","price":"Free","financial_aid":0,"official_url":"https://www.irodori.jpf.go.jp/en/"},
    {"slug":"lang-es-cervantes","title":"Spanish Online Courses – Instituto Cervantes","platform":"instituto-cervantes","description":"دورات إسبانية رسمية بمستويات مختلفة عبر شبكة معاهد Instituto Cervantes؛ التفاصيل والأسعار حسب المركز.","category":"Spanish","level":"A1–C2","language":"Spanish","duration":"Varies","free":0,"certificate_available":1,"certificate_type":"Course certificate / exam options vary","price":"Varies","financial_aid":0,"official_url":"https://cervantes.org/"},
    {"slug":"lang-tr-yunus","title":"Turkish Learning Resources","platform":"yunus-emre-institute","description":"موارد وبرامج رسمية لتعلم التركية من معهد يونس إمره، مع مستويات ومسارات تختلف حسب البرنامج والمركز.","category":"Turkish","level":"Beginner–Advanced","language":"Turkish / English","duration":"Varies","free":1,"certificate_available":1,"certificate_type":"Varies by program","price":"Varies","financial_aid":0,"official_url":"https://turkce.yee.org.tr/"},
    {"slug":"lang-ru-pushkin","title":"Russian Language Learning – Pushkin Institute","platform":"pushkin-institute","description":"موارد رقمية لتعلم الروسية من معهد بوشكين، تشمل مواد وتمارين واختبارات وبرامج لغوية حسب المسار.","category":"Russian","level":"Beginner–Advanced","language":"Russian / English","duration":"Varies","free":1,"certificate_available":1,"certificate_type":"Varies by program","price":"Varies","financial_aid":0,"official_url":"https://pushkininstitute.ru/"},
    {"slug":"lang-it-dante","title":"Italian Language Courses – Società Dante Alighieri","platform":"dante-alighieri","description":"دورات وموارد لتعلم الإيطالية عبر شبكة Società Dante Alighieri الدولية؛ المواعيد والرسوم تختلف حسب المركز.","category":"Italian","level":"A1–C2","language":"Italian","duration":"Varies","free":0,"certificate_available":1,"certificate_type":"Varies by centre","price":"Varies","financial_aid":0,"official_url":"https://www.dante.global/"},
    {"slug":"lang-nl-uva","title":"Dutch Language Courses – University of Amsterdam","platform":"university-amsterdam-dutch","description":"دورات هولندية جامعية عبر مركز اللغات بجامعة أمستردام، مع برامج منظمة ومستويات مختلفة.","category":"Dutch","level":"Beginner–Advanced","language":"Dutch / English","duration":"Varies","free":0,"certificate_available":0,"certificate_type":"","price":"Varies","financial_aid":0,"official_url":"https://www.uva.nl/en/education/other-programmes/language-courses/language-courses.html"},
    {"slug":"lang-zh-chineseplus","title":"Chinese Language Learning – Chinese Plus","platform":"chineseplus","description":"مسارات رقمية لتعلم الصينية عبر الإنترنت مع محتوى لغوي وثقافي؛ تحقق من توفر كل مسار وشروطه من المنصة.","category":"Chinese","level":"Beginner–Advanced","language":"Chinese / English","duration":"Self-paced / varies","free":1,"certificate_available":0,"certificate_type":"","price":"Varies","financial_aid":0,"official_url":"https://www.chineseplus.net/"},
]


def _opp(slug, typ, title, org, desc, country, url, *, online=0, age_min=None, age_max=None, education="International students", category="Scholarships", language="English / local language", funding="Varies; verify current call", tuition=None, accommodation=None, meals=None, travel=None, stipend=None, duration="Varies", certificate=0, deadline="Check official call", eligibility=None, requirements=None, status="check_source"):
    return {"slug":slug,"type":typ,"title":title,"organization":org,"description":desc,"country":country,"official_url":url,"online":online,"age_min":age_min,"age_max":age_max,"education_level":education,"category":category,"language":language,"funding_type":funding,"tuition_covered":tuition,"accommodation":accommodation,"meals":meals,"travel":travel,"stipend":stipend,"duration":duration,"certificate":certificate,"deadline":deadline,"eligibility":eligibility or ["راجع الجنسية والمرحلة الدراسية وشروط الدورة الحالية من المصدر الرسمي"],"requirements":requirements or ["جواز سفر أو إثبات هوية عند الحاجة","الشهادات وكشف الدرجات عند طلبهما","المستندات الإضافية المحددة في الدعوة الرسمية"],"status":status}

SUPPLEMENTAL_OPPORTUNITIES = [
    _opp("sch-france-eiffel","scholarship","France Excellence Eiffel Scholarship","Campus France / French Ministry for Europe and Foreign Affairs","منحة حكومية فرنسية مرموقة للطلاب الدوليين في الماجستير والدكتوراه والهندسة ضمن مجالات محددة. التقديم لا يتم مباشرة من الطالب إلى Campus France؛ يجب أن تتبنى مؤسسة تعليم عالٍ فرنسية الملف وتقدمه رسميًا.","France","https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",age_max=29,education="Master / Engineering / Doctorate",category="France / Scholarships",language="French / English",funding="Scholarship with living allowance and services; tuition rules depend on public national diploma",tuition=None,accommodation="Housing-search assistance / services",travel=1,stipend="€1,200/month Master; €2,000/month Doctorate from Jan 2026",duration="12–36 months depending on level",eligibility=["للماجستير: العمر حتى 29 سنة في حملة 2026 وفق المصدر الرسمي","للدكتوراه: العمر حتى 35 سنة وفق المصدر الرسمي","يجب أن تختارك وتدعمك مؤسسة تعليم عالٍ فرنسية؛ الطلب المباشر من الطالب غير مؤهل","المجالات ذات الأولوية تشمل الأحياء والصحة، الانتقال البيئي، الرياضيات والرقمنة، الهندسة، التاريخ واللغة والحضارة الفرنسية، القانون والعلوم السياسية، الاقتصاد والإدارة"],requirements=["ملف القبول لدى المؤسسة الفرنسية","السجل الأكاديمي والدرجات","السيرة الذاتية وخطاب الدافع أو مستندات المؤسسة حسب طلبها","وثائق الهوية والجنسية","أي مستندات تطلبها المؤسسة الفرنسية"],status="check_source"),
    _opp("sch-france-campus-bourses","scholarship","Campus Bourses – البحث عن منح الدراسة في فرنسا","Campus France","قاعدة رسمية للبحث عن المنح والمساعدات المتاحة للطلاب الدوليين في فرنسا. يمكن تصفية النتائج حسب الجنسية والمجال ومستوى الدراسة، وهي أفضل نقطة بداية للعثور على منح فرنسية متعددة بدل الاعتماد على منحة واحدة فقط.","France","https://campusbourses.campusfrance.org/",education="Secondary / Bachelor / Master / Doctorate",category="France / Scholarship Directory",language="French / English",funding="Varies by scholarship",duration="Varies",eligibility=["الأهلية تختلف لكل منحة وجهة مانحة","استخدم فلاتر الجنسية والمجال والمرحلة الدراسية"],requirements=["تختلف حسب المنحة؛ راجع صفحة الجهة المانحة"],status="check_source"),
    _opp("sch-france-major","scholarship","France Excellence Major","AEFE / France Education International","برنامج للطلاب المتفوقين من المدارس الفرنسية في الخارج لمتابعة التعليم العالي في فرنسا. الأهلية والتقديم مرتبطان بمسار المدارس الفرنسية بالخارج والجهات التعليمية المشاركة.","France / French schools abroad","https://www.aefe.fr/",education="French secondary school / future higher education",category="France / Secondary",language="French",funding="Scholarship support; verify current campaign",duration="Varies",eligibility=["البرنامج مرتبط بالطلاب المتفوقين في المدارس الفرنسية بالخارج؛ تحقق من شروط الحملة الحالية","الترشيح والإجراءات تتم وفق المؤسسات والجهات التعليمية المعنية"],requirements=["السجل الدراسي","وثائق المدرسة الفرنسية في الخارج","الوثائق التي تحددها AEFE في الحملة"],status="check_source"),
    _opp("sch-germany-daad-database","scholarship","DAAD Scholarship Database","DAAD","قاعدة DAAD الرسمية التي تجمع برامج منح DAAD وعروض جهات تمويل مختارة للطلاب والباحثين الدوليين. يمكن البحث حسب دولة الإقامة والمستوى والمجال وهدف المنحة.","Germany / Global","https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/",education="Undergraduate / Graduate / Doctoral / Researchers",category="Germany / Scholarships",language="English / German",funding="Varies by program",duration="Varies",eligibility=["كل برنامج له شروط جنسية ومرحلة ومجال مختلفة","راجع صفحة البرنامج المحدد قبل التقديم"],requirements=["تختلف حسب البرنامج؛ قد تشمل الدرجات والسيرة الذاتية وخطة الدراسة وإثبات اللغة"],status="check_source"),
    _opp("sch-netherlands-nl","scholarship","NL Scholarship","Study in NL / Dutch Ministry of Education and participating institutions","منحة للطلاب الدوليين من خارج المنطقة الاقتصادية الأوروبية الراغبين في دراسة بكالوريوس أو ماجستير بدوام كامل في مؤسسة هولندية مشاركة. قيمة المنحة الحالية المذكورة للموسم 2026–2027 هي 5,000 يورو في السنة الأولى وليست منحة تغطي كامل الرسوم.","Netherlands","https://www.studyinnl.org/finances/nl-scholarship",education="Bachelor / Master",category="Netherlands / Scholarships",language="English / Dutch",funding="Partial scholarship",tuition=0,stipend="€5,000 in the first year according to 2026–2027 official page",duration="First year",eligibility=["الجنسية من خارج EEA","التقديم لبرنامج بكالوريوس أو ماجستير بدوام كامل في مؤسسة مشاركة","شروط المؤسسة المضيفة تختلف حسب البرنامج"],requirements=["طلب القبول في المؤسسة الهولندية","الوثائق الأكاديمية والهوية حسب الجامعة","أي مستندات إضافية تحددها الجامعة"],status="check_source"),
    _opp("sch-hungary-stipendium","scholarship","Stipendium Hungaricum","Tempus Public Foundation / Government of Hungary","برنامج المنح الحكومية المجرية للطلاب الدوليين، ويشمل برامج بكالوريوس وماجستير ودكتوراه وبرامج غير درجة بحسب الدعوة السنوية والدول الشريكة.","Hungary","https://stipendiumhungaricum.hu/apply/",education="Bachelor / Master / Doctorate / Non-degree",category="Hungary / Scholarships",language="English / Hungarian",funding="Scholarship package; details vary by call",tuition=1,accommodation=1,stipend="According to current call",duration="Varies by program",eligibility=["الجنسية والدول المؤهلة تعتمد على الدعوة والشريك المرسل","اختيار برنامج ومؤسسة من القوائم المؤهلة","الشروط الأكاديمية تختلف حسب البرنامج"],requirements=["الشهادات وكشف الدرجات","إثبات اللغة إذا طلبه البرنامج","وثائق الهوية","خطابات أو مستندات إضافية حسب البرنامج"],status="check_source"),
    _opp("sch-korea-gks","scholarship","Global Korea Scholarship (GKS)","National Institute for International Education / Government of Korea","منحة الحكومة الكورية للطلاب الدوليين وتشمل مسارات البكالوريوس والدراسات العليا. قد تشمل التدريب اللغوي الكوري والرسوم الدراسية وتذاكر السفر وبدلات الدراسة وفق المسار.","South Korea","https://www.gks.go.kr/en/plan/scholarship.do",age_max=25,education="High School graduate / Bachelor / Master / Doctorate",category="Korea / Scholarships",language="Korean / English",funding="Fully funded scholarship package",tuition=1,travel=1,stipend="Study allowances according to GKS track",duration="2–6 years depending on degree",eligibility=["للبكالوريوس: المتقدم ووالداه يحملون جنسيات غير كورية","للبكالوريوس في صفحة GKS الحالية: أقل من 25 سنة","للبكالوريوس: خريج ثانوي أو ما يعادله؛ بعض المسارات تقبل خريجي الدبلوم","أداء أكاديمي 80% أو أعلى في المسار المذكور للمرحلة"],requirements=["جواز السفر ووثائق الجنسية","الشهادة وكشف الدرجات","وثائق الوالدين عند طلب إثبات الجنسية العائلية","مستندات إضافية حسب Embassy Track أو University Track"],status="check_source"),
    _opp("sch-japan-mext","scholarship","MEXT – Japanese Government Scholarship","Ministry of Education, Culture, Sports, Science and Technology (MEXT)","منحة الحكومة اليابانية الرسمية وتشمل سبعة أنواع من المسارات، منها طلاب البكالوريوس والبحث والتدريب والمدارس المتخصصة. التقديم يكون عادةً عبر ترشيح السفارة أو ترشيح الجامعة وفق النوع.","Japan","https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",age_max=25,education="Undergraduate / Research / Specialized Training / Other MEXT tracks",category="Japan / Scholarships",language="Japanese / English",funding="Government scholarship",tuition=1,travel=1,stipend="Monthly allowance varies by MEXT track",duration="Varies by track",eligibility=["طلاب البكالوريوس: أقل من 25 سنة وفق الصفحة الرسمية الحالية، مع إكمال 12 سنة تعليم أو ما يعادل الثانوية اليابانية","الشروط تختلف حسب نوع MEXT؛ اتبع أحدث دليل رسمي"],requirements=["جواز السفر","الشهادة وكشف الدرجات","وثائق اللغة أو الاختبارات إذا طلبها المسار","نماذج MEXT الرسمية"],status="check_source"),
    _opp("sch-russia-government-quota","scholarship","Russian Government Scholarship / Education in Russia Quota","Government of the Russian Federation","مسار رسمي للتقديم على التعليم في روسيا ضمن الحصة الحكومية الممولة من الميزانية الفدرالية. منصة Education in Russia تتضمن نموذج التقديم ووثائق وإجراءات الاختيار، وتختلف التفاصيل حسب الدولة والبرنامج.","Russia","https://education-in-russia.com/",education="Bachelor / Master / Doctorate / Other programs",category="Russia / Scholarships",language="Russian / English",funding="Tuition-free quota; other support depends on program and quota",tuition=1,accommodation=None,travel=None,stipend="Depends on institution/program",duration="Varies",eligibility=["الجنسية والدولة وإجراءات الاختيار تعتمد على الحصة المخصصة","قد توجد اختبارات أو منافسة ملفات أو مقابلة بحسب الدولة والبرنامج","قد يتطلب البرنامج لغة روسية أو سنة تحضيرية"],requirements=["نسخة جواز السفر","وثائق التعليم وكشف الدرجات","نتائج الاختبارات أو الاختيار","ترجمة معتمدة لبعض الوثائق إلى الروسية عند طلبها","الوثائق الطبية المطلوبة لبعض البرامج"],status="check_source"),
    _opp("vol-smithsonian","volunteer","Smithsonian Volunteer Opportunities","Smithsonian Institution","فرص تطوع ومشاركة تعليمية وعلمية لدى مؤسسة Smithsonian، وتختلف البرامج بين المتاحف والمراكز والمشاريع. يجب التحقق من العمر والموقع ومتطلبات كل فرصة قبل التقديم.","USA / Selected locations","https://www.si.edu/volunteer",education="Students / Youth / Volunteers",category="Volunteering / Science / Culture",language="English",funding="Volunteer; no general salary",duration="Varies",eligibility=["العمر والمتطلبات تختلف حسب فرصة Smithsonian المحددة","بعض الفرص حضورية وبعضها قد يكون ذا طبيعة رقمية أو بحثية"],requirements=["طلب أو نموذج اهتمام حسب الفرصة","السيرة الذاتية أو بيانات المتطوع عند الطلب","موافقة ولي الأمر إذا اشترطتها الفرصة"],status="check_source"),
    _opp("vol-national-parks","volunteer","National Park Service Volunteer Opportunities","U.S. National Park Service","منصة رسمية لفرص التطوع في الحدائق الوطنية الأمريكية، تشمل مشاريع خدمة مجتمعية وبيئية وتعليمية بحسب الحديقة والبرنامج.","USA","https://www.nps.gov/getinvolved/volunteer.htm",education="Students / Youth / Volunteers",category="Volunteering / Environment",language="English",funding="Volunteer; expenses vary",duration="Varies",eligibility=["الشروط والعمر يختلفان حسب الفرصة والحديقة","بعض الأدوار تحتاج تدريبًا أو التزامًا ميدانيًا"],requirements=["نموذج التطوع أو بيانات التواصل","إثبات الهوية عند الحاجة","أي فحوص أو تدريب تحدده الفرصة"],status="check_source"),
    _opp("vol-redcross","volunteer","American Red Cross Volunteer","American Red Cross","منصة رسمية للتطوع في مجالات خدمة المجتمع والاستجابة للكوارث والصحة والدعم المجتمعي. تختلف الأدوار والأعمار والمتطلبات حسب الفرع والدور.","USA / Local and selected remote roles","https://www.redcross.org/volunteer/become-a-volunteer.html",education="Students / Youth / Volunteers",category="Volunteering / Community",language="English",funding="Volunteer; no general salary",duration="Varies",eligibility=["تختلف حسب الدور والعمر والموقع","قد يتطلب بعض الأدوار تدريبًا أو فحصًا خلفيًا"],requirements=["طلب التطوع","بيانات الهوية والتواصل","تدريب أو فحوص عند اشتراطها"],status="check_source"),
    _opp("vol-rotary","volunteer","Rotary Volunteer Opportunities","Rotary International","بوابة رسمية للتعرف على فرص وأنشطة Rotary التطوعية والمجتمعية والبيئية والتعليمية عبر الأندية والمشاريع المحلية والدولية.","Global","https://www.rotary.org/en/get-involved/volunteer",education="Students / Youth / Volunteers",category="Volunteering / Community",language="Multiple",funding="Volunteer; varies",duration="Varies",eligibility=["كل مشروع يحدد شروط المشاركة والعمر والموقع","قد تكون المشاركة عبر نادٍ محلي أو مشروع محدد"],requirements=["بيانات التواصل","أي نموذج أو مستند يطلبه النادي أو المشروع"],status="check_source"),
]

SUPPLEMENTAL_OPPORTUNITIES.extend([
    _opp("sch-oxford-reach","scholarship","Reach Oxford Scholarship","University of Oxford","منحة جامعية لطلاب البكالوريوس من الدول منخفضة الدخل الذين لا يستطيعون الدراسة في بلدانهم لأسباب مالية أو تعليمية. يجب أولًا التقديم إلى أكسفورد والحصول على عرض قبول قبل النظر في المنحة.","United Kingdom","https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-bursaries-and-scholarships/reach-oxford",education="Undergraduate",category="UK / Oxford / Scholarships",language="English",funding="Full support for selected undergraduate scholars",tuition=1,travel=1,stipend="Living-cost grant",duration="3–4 years",eligibility=["طالب دولي من دولة مؤهلة حسب قائمة أكسفورد","الحصول على عرض قبول في برنامج بكالوريوس مؤهل","تميز أكاديمي وحاجة مالية والتزام اجتماعي وفق معايير البرنامج","المنحة ليست متاحة للطب"],requirements=["طلب القبول في أكسفورد","السجل الدراسي","بيانات الحاجة المالية","مستندات القبول والهوية حسب الجامعة"],status="check_source"),
    _opp("sch-utoronto-pearson","scholarship","Lester B. Pearson International Scholarship","University of Toronto","منحة جامعية قوية للطلاب الدوليين في المرحلة الثانوية النهائية الراغبين في بدء بكالوريوس بجامعة تورنتو. في دورة 2027 يجب أن يكون الطالب في السنة النهائية من الثانوية أو متخرجًا منذ يونيو 2026، ويجب أن ترشحه مدرسته.","Canada","https://future.utoronto.ca/pearson-scholarships",education="Final-year Secondary / Undergraduate entry",category="Canada / Scholarships",language="English",funding="Full undergraduate scholarship",tuition=1,accommodation=1,stipend="Full residence support",duration="4 years",eligibility=["طالب دولي يحتاج تصريح دراسة كندي","في السنة النهائية من الثانوية في 2026/2027 أو تخرج منذ يونيو 2026 وفق صفحة 2027","البدء في سبتمبر 2027","ترشيح الطالب من المدرسة شرط أساسي"],requirements=["ترشيح المدرسة","طلب القبول في University of Toronto","وثائق الثانوية","طلب Pearson الخاص بعد الترشيح"],deadline="2026-10-09 school nomination; 2026-10-16 U of T admission; 2026-11-06 scholarship application",status="check_source"),
    _opp("sch-ucl-global-undergraduate","scholarship","UCL Global Undergraduate Scholarship","University College London","منحة UCL العالمية للبكالوريوس للطلاب الدوليين من ذوي الدخل المنخفض، وتهدف إلى دعم الوصول إلى الدراسة في UCL. يجب تقديم طلب القبول في UCL أولًا حتى تصبح مؤهلًا لتقديم طلب المنحة.","United Kingdom","https://www.ucl.ac.uk/scholarships/ucl-global-scholarships",education="Undergraduate",category="UK / UCL / Scholarships",language="English",funding="Tuition and/or living-cost support depending on award",tuition=None,duration="Degree duration / award terms",eligibility=["طالب دولي مؤهل للرسوم الخارجية","التقديم إلى برنامج بكالوريوس مؤهل في UCL","حاجة مالية وشروط البرنامج الحالية"],requirements=["طلب القبول في UCL","الوثائق الأكاديمية","طلب المنحة بعد استيفاء شرط التقديم"],status="check_source"),
    _opp("program-technovation-girls","program","Technovation Girls","Technovation","برنامج عالمي مجاني للفتيات والمشاركات المؤهلات لتعلم البرمجة والذكاء الاصطناعي وبناء تطبيق وحل مشكلة حقيقية ثم المشاركة في مسابقة عالمية. التسجيل الموسمي يفتح ويغلق حسب الدورة.","Global / Online","https://technovationchallenge.org/get-involved/students/",online=1,age_min=8,age_max=18,education="School students / Girls and eligible participants",category="Technology / AI / Entrepreneurship",language="Multiple",funding="Free program",duration="Seasonal",certificate=0,eligibility=["البرنامج موجّه للفتيات ومشاركات مؤهلات وفق قواعد الموسم","يجب متابعة فتح التسجيل للموسم الحالي"],requirements=["إنشاء حساب","اختيار فريق أو مسار حسب الموسم","مشروع تقني وخطة عمل حسب متطلبات التحدي"],status="check_source"),
    _opp("competition-breakthrough-2026","competition","Breakthrough Junior Challenge 2026","Breakthrough Prize Foundation","مسابقة عالمية لطلاب المدارس الثانوية لإنشاء فيديو علمي مدته دقيقتان يشرح فكرة مهمة في الفيزياء أو الرياضيات أو علوم الحياة بطريقة مبتكرة.","Global / Online","https://breakthroughjuniorchallenge.org/enter",online=1,age_min=13,age_max=18,education="High School",category="Science / Physics / Mathematics / Life Sciences",language="English",funding="$250,000 post-secondary scholarship for winner",duration="Annual",certificate=0,deadline="2026-09-15",eligibility=["العمر 13–18 وفق تواريخ دورة 2026","تقديم فيديو باللغة الإنجليزية لا يتجاوز دقيقتين","إكمال مراجعة Peer-to-Peer المطلوبة للمنافسة على الجائزة"],requirements=["فيديو أصلي","بيانات المدرسة والطالب","رابط YouTube للفيديو","المشاركة في تقييم أعمال طلاب آخرين"],status="open"),
    _opp("vol-european-solidarity-corps","volunteer","European Solidarity Corps Volunteering","European Union / European Youth Portal","برنامج تطوع ممول من الاتحاد الأوروبي للشباب، يتيح مشاريع تضامن وتطوع داخل أوروبا وخارجها في مجالات اجتماعية وبيئية وصحية ورقمية وإنسانية. الأنشطة غير مدفوعة كراتب، لكن تكاليف النشاط تكون مغطاة وفق قواعد البرنامج.","Europe / Partner countries","https://youth.europa.eu/solidarity/young-people/volunteering_en",age_min=18,age_max=30,education="Young people",category="Volunteering / Europe",language="Multiple",funding="Funded volunteering activity; support depends on project",accommodation=1,meals=1,travel=1,stipend="Pocket money according to program rules",duration="2 weeks–12 months",eligibility=["العمر 18–30 للتطوع العام، و18–35 لبعض أنشطة المساعدة الإنسانية","التسجيل وإنشاء EU Login وملف European Solidarity Corps","اختيار مشروع مؤهل؛ التسجيل لا يضمن المشاركة"],requirements=["حساب EU Login","ملف شخصي في European Solidarity Corps","وثائق المشروع التي قد يطلبها المضيف"],status="check_source"),
    _opp("program-first-ftc-add","program","FIRST Tech Challenge","FIRST","برنامج STEM للطلاب يركز على تصميم وبرمجة الروبوتات والعمل الجماعي والمنافسة المحلية والدولية عبر فرق مدرسية ومجتمعية.","Global","https://www.firstinspires.org/programs/ftc/get-started",education="Grades 7–12",category="Robotics / Programming / Engineering",language="English / Multiple",funding="Program fees and team costs vary by region",duration="Seasonal",eligibility=["البرنامج مخصص لطلاب المدارس ضمن الفئة العمرية والقواعد المحلية","المشاركة تتم عبر فريق أو منظمة مسجلة"],requirements=["فريق ومشرف","التسجيل الرسمي","التجهيزات التي يحددها البرنامج أو الفريق"],status="check_source"),
    _opp("intern-nasa-stem","internship","NASA STEM Engagement / Internship Opportunities","NASA","بوابة NASA الرسمية لفرص STEM والتدريب والبرامج التعليمية. الأهلية تختلف حسب البرنامج؛ بعض فرص التدريب مخصصة لطلاب جامعات بينما توجد برامج STEM أخرى للطلاب الأصغر سنًا.","USA / Selected programs","https://stemgateway.nasa.gov/",education="Students / Undergraduate / Graduate depending on program",category="STEM / Space / Research",language="English",funding="Varies by program",duration="Varies",eligibility=["الشروط تختلف حسب الفرصة والمرحلة الدراسية والجنسية","لا تفترض أن كل فرص NASA تقبل طلاب الثانوية؛ راجع الإعلان المحدد"],requirements=["سجل أكاديمي","سيرة ذاتية أو بيانات طالب حسب البرنامج","متطلبات الجنسية أو الإقامة حسب الفرصة"],status="check_source"),
])
