import sqlite3, json
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / 'opportunities.db'
TODAY = datetime.now(timezone.utc).date().isoformat()

PLATFORMS = [
    dict(slug='google-skillshop', name='Google Skillshop', description='منصة Google الرسمية للتدريب على منتجات Google الإعلانية والتحليلات ومنتجات الأعمال، مع مسارات تدريب واختبارات اعتماد لبعض المنتجات.', official_url='https://skillshop.withgoogle.com/', courses_url='https://skillshop.withgoogle.com/googleads/', certificates_url='https://skillshop.withgoogle.com/', country='Global', categories=['Digital Marketing','Analytics','Google'], free_courses_available=1, certificates_available=1, financial_aid_available=0, free_access_guide='التدريب على Google Ads متاح مجانًا. تحقق من صفحة المسار والاختبار قبل التسجيل لأن نوع الاعتماد يختلف حسب المنتج.', source='https://skillshop.withgoogle.com/googleads/'),
    dict(slug='google-for-education', name='Google for Education', description='مركز Google الرسمي للتعلم في مجال التعليم، ويضم دورات مجانية وشهادات Google Certified Educator وGemini Certified Student وفق الفئة العمرية أو الدور.', official_url='https://edu.google.com/learning-center/', courses_url='https://edu.google.com/learning-center/', certificates_url='https://edu.google.com/learning-center/certifications/', country='Global', categories=['Education','AI','Google Workspace'], free_courses_available=1, certificates_available=1, financial_aid_available=0, free_access_guide='الدورات الإلكترونية في Learning Center مجانية. بعض الشهادات الرسمية مثل Google Certified Educator وGemini Certified Student موصوفة حاليًا بأنها مجانية مع شروط أهلية محددة.', source='https://edu.google.com/learning-center/certifications/'),
    dict(slug='ibm-skillsbuild', name='IBM SkillsBuild', description='منصة IBM التعليمية المجانية للطلاب الثانويين والجامعيين والبالغين، وتقدم تعلمًا في الذكاء الاصطناعي والأمن السيبراني والبيانات ومهارات العمل مع بيانات اعتماد رقمية.', official_url='https://skillsbuild.org/', courses_url='https://skillsbuild.org/learners', certificates_url='https://skillsbuild.org/learners', country='Global', categories=['AI','Cybersecurity','Data','Career Skills'], free_courses_available=1, certificates_available=1, financial_aid_available=0, free_access_guide='أنشئ حسابًا مجانيًا واستكشف مسارات High School أو University أو Adult Learners، ثم أكمل الأنشطة المؤهلة للحصول على بيانات الاعتماد الرقمية المتاحة.', source='https://skillsbuild.org/'),
    dict(slug='harvard-cs50', name='Harvard CS50', description='منصة CS50 الرسمية من Harvard University التي توفر مقررات OpenCourseWare مجانية، وبعض مقرراتها تمنح شهادة CS50 مجانية عند استيفاء متطلبات الإكمال.', official_url='https://cs50.harvard.edu/x/', courses_url='https://cs50.harvard.edu/x/', certificates_url='https://cs50.harvard.edu/x/certificate/', country='USA / Online', categories=['Computer Science','Programming','Python','Web'], free_courses_available=1, certificates_available=1, financial_aid_available=0, free_access_guide='ادرس المقرر مجانًا عبر OpenCourseWare، وأنجز الواجبات والمشروع النهائي وفق المتطلبات؛ شهادة CS50 المجانية تختلف عن شهادة edX الموثقة المدفوعة.', source='https://cs50.harvard.edu/x/certificate/'),
    dict(slug='cisco-networking-academy', name='Cisco Networking Academy', description='أكاديمية Cisco الرسمية التي تقدم دورات ذاتية مجانية في الشبكات والأمن السيبراني والبرمجة والمهارات الرقمية.', official_url='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html', courses_url='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html', certificates_url='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html', country='Global', categories=['Networking','Cybersecurity','Programming'], free_courses_available=1, certificates_available=0, financial_aid_available=0, free_access_guide='ابدأ من Cisco Networking Academy واختر الدورات المجانية ذاتية التعلم. الشهادات المهنية الرسمية من Cisco مثل CCNA لها مسار امتحان منفصل وليست مجانية لمجرد إكمال الدورة.', source='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html'),
]

COURSES = [
    dict(slug='google-ads-free-training', title='تدريب Google Ads المجاني', platform='google-skillshop', description='تدريب رسمي مجاني من Google Skillshop لتعلم أساسيات Google Ads وفهم إنشاء الحملات وإدارتها وتحسين الأداء. مناسب للمبتدئين في التسويق الرقمي، ويمكن استخدامه كمدخل لمسارات اعتماد Google Ads.', category='التسويق الرقمي', level='مبتدئ', language='الإنجليزية', duration='مرن حسب المسار', free=1, cert=1, cert_type='اعتماد Google Ads حسب الاختبار والمسار المتاح', price='مجاني', aid=0, url='https://skillshop.withgoogle.com/googleads/'),
    dict(slug='google-gemini-certified-student', title='Gemini Certified Student من Google for Education', platform='google-for-education', description='اعتماد Google مخصص للطلاب لإثبات إتقان أساسيات استخدام Gemini في التعلم. الصفحة الرسمية تذكر أن الشهادة صالحة لثلاث سنوات ومجانية، وأن نسخة K-12 متاحة للطلاب من عمر 13 عامًا فأكثر، مع تدريب تحضيري قبل الاختبار.', category='الذكاء الاصطناعي', level='طالب', language='الإنجليزية', duration='حسب التدريب والاختبار', free=1, cert=1, cert_type='Google Certificate + Badge', price='مجاني', aid=0, url='https://edu.google.com/learning-center/certifications/'),
    dict(slug='google-certified-educator-level-1', title='Google Certified Educator Level 1', platform='google-for-education', description='اعتماد Google for Education للمعلمين لإثبات إتقان أدوات Google المستخدمة في الصف. التدريب التحضيري متاح من Learning Center، والصفحة الرسمية تصف الشهادة بأنها مجانية وصالحة لثلاث سنوات.', category='Google Workspace والتعليم', level='مبتدئ', language='الإنجليزية', duration='مرن', free=1, cert=1, cert_type='Google Certified Educator Level 1', price='مجاني', aid=0, url='https://edu.google.com/learning-center/certifications/'),
    dict(slug='google-generative-ai-introduction', title='Introduction to Generative AI — Google Cloud', platform='google-skillshop', description='دورة تمهيدية رسمية من Google Cloud Skills Boost تشرح الذكاء الاصطناعي التوليدي ونماذج اللغة والتطبيقات وأدوات Google لبناء تطبيقات GenAI. الصفحة الرسمية تعرضها حاليًا بسعر No cost، وتذكر أن إكمال العناصر المطلوبة قد يمنح شارة إكمال؛ بعض المختبرات في مسارات أخرى قد تتطلب اشتراكًا أو رصيدًا.', category='الذكاء الاصطناعي', level='مبتدئ', language='الإنجليزية، الإسبانية، الفرنسية، الألمانية، الإيطالية، اليابانية، الكورية، الصينية وغيرها', duration='45 دقيقة', free=1, cert=1, cert_type='Completion Badge حسب متطلبات الدورة', price='مجاني للدورة المحددة؛ تحقق من متطلبات المختبرات', aid=0, url='https://www.cloudskillsboost.google/course_templates/536FREE'),
    dict(slug='google-cloud-core-infrastructure', title='Google Cloud Fundamentals: Core Infrastructure', platform='google-skillshop', description='مسار رسمي من Google Cloud لفهم البنية الأساسية للخدمات السحابية مثل الحوسبة والتخزين والشبكات. المادة التعليمية متاحة مجانًا في كثير من الحالات، لكن Google تنبه إلى أن المختبرات العملية قد تحتاج اشتراكًا أو أرصدة، لذلك لا يُعرض هنا كدورة مجانية بالكامل بكل مختبراتها.', category='الحوسبة السحابية', level='مبتدئ', language='الإنجليزية، الفرنسية، الألمانية، الإسبانية، الإيطالية، اليابانية، الكورية، الصينية وغيرها', duration='متغير', free=1, cert=1, cert_type='Badge/Completion حسب متطلبات الدورة', price='المحتوى غالبًا مجاني؛ بعض المختبرات قد تتطلب رصيدًا', aid=0, url='https://www.cloudskillsboost.google/course_templates/60?locale=en'),
    dict(slug='microsoft-azure-cloud-concepts', title='Microsoft Learn — وصف مفاهيم السحابة Azure', platform='microsoft-learn', description='مسار Microsoft Learn للمبتدئين في مفاهيم الحوسبة السحابية، وهو الجزء الأول من سلسلة Azure Fundamentals. يتكون من ثلاث وحدات ويشرح نماذج السحابة والمسؤولية المشتركة والاستهلاك والخدمات الأساسية. التدريب نفسه مجاني، ويمكن أن يساعد في التحضير لـ AZ-900، بينما اختبار الشهادة الرسمي منفصل.', category='الحوسبة السحابية', level='مبتدئ', language='متعدد اللغات', duration='56 دقيقة', free=1, cert=0, cert_type='إنجاز Microsoft Learn؛ ليس شهادة AZ-900 بحد ذاته', price='مجاني', aid=0, url='https://learn.microsoft.com/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/'),
    dict(slug='microsoft-azure-architecture-services', title='Microsoft Learn — Azure Architecture and Services', platform='microsoft-learn', description='مسار من خمس وحدات يشرح المكونات المعمارية الأساسية لـ Azure وخدمات الحوسبة والشبكات والتخزين والهوية والأمان. المسار مجاني ومناسب للمبتدئ ويستخدم للتحضير لـ AZ-900، مع توضيح أن الامتحان الرسمي للحصول على Microsoft Certified: Azure Fundamentals منفصل.', category='Azure', level='مبتدئ', language='متعدد اللغات', duration='2 ساعة و48 دقيقة', free=1, cert=0, cert_type='إنجاز/XP على Microsoft Learn؛ اختبار AZ-900 منفصل', price='مجاني', aid=0, url='https://learn.microsoft.com/en-us/training/paths/azure-fundamentals-describe-azure-architecture-services/'),
    dict(slug='microsoft-azure-management-governance', title='Microsoft Learn — Azure Management and Governance', platform='microsoft-learn', description='مسار مجاني من Microsoft يشرح إدارة التكاليف والحوكمة والامتثال وإدارة الموارد والمراقبة في Azure. يتكون من أربع وحدات ويشكل الجزء الثالث من سلسلة Azure Fundamentals.', category='Azure', level='مبتدئ', language='متعدد اللغات', duration='1 ساعة و21 دقيقة', free=1, cert=0, cert_type='إنجاز/XP على Microsoft Learn', price='مجاني', aid=0, url='https://learn.microsoft.com/en-us/training/paths/describe-azure-management-governance/'),
    dict(slug='microsoft-azure-guided-projects', title='Microsoft Learn — مشاريع Azure العملية الموجهة', platform='microsoft-learn', description='مسار عملي مجاني يتضمن مشاريع موجهة لتطبيق مهارات Azure، مثل استضافة موقع ثابت باستخدام Azure Blob Storage. مناسب للطالب الذي يريد تحويل الدراسة النظرية إلى مشروع يمكن عرضه في ملفه الشخصي.', category='الحوسبة السحابية', level='مبتدئ', language='متعدد اللغات', duration='5 ساعات و8 دقائق', free=1, cert=0, cert_type='إنجاز/XP على Microsoft Learn', price='مجاني', aid=0, url='https://learn.microsoft.com/en-us/training/paths/introduction-cloud-infrastructure-apply-azure-skills-guided-projects/'),
    dict(slug='huawei-ict-academy-learning', title='Huawei ICT Academy — مسارات التعلم الرسمية', platform='huawei', description='كتالوج Huawei ICT Academy الرسمي للتعلم في الشبكات والسحابة والذكاء الاصطناعي ومجالات ICT. الأكاديمية شراكة بين Huawei ومؤسسات تعليمية، وتوضح Huawei أن الوصول والدروس العملية قد يختلفان حسب الأكاديمية والبلد؛ لذلك لا نعد هذا المحتوى مجانيًا للجميع، بل نوضح أن توفره وشروط الشهادة يجب التحقق منهما لدى الأكاديمية الشريكة.', category='الشبكات وICT', level='طالب / جامعة', language='الإنجليزية ولغات محلية حسب الأكاديمية', duration='حسب المقرر', free=0, cert=1, cert_type='مسارات تؤهل لشهادات Huawei؛ الامتحان والشهادة حسب البرنامج', price='حسب الأكاديمية والبرنامج', aid=0, url='https://e.huawei.com/en/talent/ict-academy/'),
    dict(slug='huawei-talent-learning', title='Huawei Talent — Online Courses and Learning Resources', platform='huawei', description='بوابة Huawei Talent الرسمية التي تجمع التعلم الإلكتروني والكتب ودورات الشهادات ومسارات التطوير المهني. المواد التعليمية قد تكون متاحة عبر البوابة، لكن امتحانات شهادات Huawei مثل HCIA/HCIP/HCIE لها إجراءات امتحان منفصلة، لذلك لا نخلط بين دراسة المحتوى والحصول على الشهادة.', category='Huawei ICT', level='مبتدئ إلى متقدم', language='الإنجليزية', duration='متغير', free=1, cert=0, cert_type='التعلم لا يساوي شهادة مهنية تلقائيًا', price='تحقق من كل مقرر', aid=0, url='https://e.huawei.com/en/talent/learning/'),
    dict(slug='harvard-cs50x-2026', title='Harvard CS50x 2026 — مقدمة علوم الحاسوب', platform='harvard-cs50', description='المقرر الأشهر من Harvard في علوم الحاسوب، متاح مجانًا عبر OpenCourseWare. يمر على Scratch وC والخوارزميات وهياكل البيانات وPython وSQL وHTML/CSS/JavaScript وFlask والذكاء الاصطناعي. عند إكمال المتطلبات والحصول على 70% على الأقل في التمارين والمختبرات والمشروع النهائي، يحق للطالب طلب شهادة CS50 المجانية؛ شهادة edX الموثقة منفصلة.', category='علوم الحاسوب والبرمجة', level='مبتدئ', language='الإنجليزية', duration='11 أسبوعًا تقريبًا', free=1, cert=1, cert_type='Free CS50 Certificate؛ Verified edX Certificate منفصل ومدفوع', price='المقرر والشهادة CS50 المجانية: مجانيان', aid=0, url='https://cs50.harvard.edu/x/'),
    dict(slug='harvard-cs50p-python', title='Harvard CS50P — البرمجة باستخدام Python', platform='harvard-cs50', description='مقرر Harvard كامل يركز على Python من الدوال والمتغيرات والشروط والحلقات إلى الاختبارات والملفات والتعبيرات النمطية والبرمجة الكائنية. يمكن دراسته مجانًا، ومع استيفاء متطلبات المقرر والمشروع النهائي يمكن الحصول على شهادة CS50 مجانية.', category='Python والبرمجة', level='مبتدئ', language='الإنجليزية', duration='10 أسابيع تقريبًا', free=1, cert=1, cert_type='Free CS50 Certificate؛ Verified edX Certificate منفصل', price='مجاني', aid=0, url='https://cs50.harvard.edu/python/'),
    dict(slug='harvard-cs50-web', title='Harvard CS50 Web — Web Programming with Python and JavaScript', platform='harvard-cs50', description='مقرر متقدم نسبيًا بعد أساسيات علوم الحاسوب، يركز على برمجة الويب باستخدام Python وJavaScript ومفاهيم تطبيقات الويب. CS50 يذكر أن إكمال المشاريع، بما فيها المشروع النهائي، يؤهل لشهادة CS50 مجانية، بينما الشهادة الموثقة من edX منفصلة.', category='تطوير الويب', level='متوسط', language='الإنجليزية', duration='متغير', free=1, cert=1, cert_type='Free CS50 Certificate؛ Verified edX Certificate منفصل', price='مجاني', aid=0, url='https://cs50.harvard.edu/web/'),
    dict(slug='ibm-exploring-ai', title='IBM SkillsBuild — Exploring Artificial Intelligence', platform='ibm-skillsbuild', description='مقدمة عملية للذكاء الاصطناعي من IBM SkillsBuild، مناسبة للطلاب وتشرح كيف تعمل الأنظمة الذكية وأمثلة استخدامها. المنصة مجانية وتقدم بيانات اعتماد رقمية ضمن الكتالوج عند استيفاء متطلبات النشاط المؤهل.', category='الذكاء الاصطناعي', level='مبتدئ', language='العربية، الإنجليزية، الفرنسية، الإيطالية، اليابانية، الإسبانية وغيرها', duration='90 دقيقة', free=1, cert=1, cert_type='Digital Credential حسب المسار', price='مجاني', aid=0, url='https://skillsbuild.org/students/try-it-before-you-register'),
    dict(slug='ibm-exploring-cybersecurity', title='IBM SkillsBuild — Exploring Cybersecurity', platform='ibm-skillsbuild', description='دورة تمهيدية مجانية لاستكشاف الأمن السيبراني، وتشرح أساسيات حماية البيانات والمخاطر والمهارات المطلوبة للمجال. IBM توفرها للمتعلمين بلغات متعددة، ويمكن للمسجلين الوصول إلى كتالوج أوسع وبيانات اعتماد رقمية.', category='الأمن السيبراني', level='مبتدئ', language='العربية، الإنجليزية، الفرنسية، الإيطالية، اليابانية، الإسبانية وغيرها', duration='80 دقيقة', free=1, cert=1, cert_type='Digital Credential حسب النشاط المؤهل', price='مجاني', aid=0, url='https://skillsbuild.org/students/try-it-before-you-register'),
    dict(slug='ibm-exploring-data', title='IBM SkillsBuild — Exploring Data', platform='ibm-skillsbuild', description='مقدمة مجانية في فهم البيانات وكيفية استخدامها، وهي مناسبة للطلاب الذين يريدون اكتشاف مجال تحليل البيانات قبل الدخول في مسارات أكثر تقدمًا.', category='تحليل البيانات', level='مبتدئ', language='العربية، الإنجليزية، الفرنسية، الإيطالية، اليابانية، الإسبانية وغيرها', duration='85 دقيقة', free=1, cert=1, cert_type='Digital Credential حسب النشاط المؤهل', price='مجاني', aid=0, url='https://skillsbuild.org/students/try-it-before-you-register'),
    dict(slug='cisco-introduction-cybersecurity', title='Cisco Networking Academy — Introduction to Cybersecurity', platform='cisco-networking-academy', description='دورة Cisco مجانية ذاتية التعلم مدتها المنشورة حاليًا نحو 6 ساعات، تعرّف الطالب بمجال الأمن السيبراني وأسباب أهميته ومساراته المهنية.', category='الأمن السيبراني', level='مبتدئ', language='الإنجليزية', duration='6 ساعات', free=1, cert=0, cert_type='إتمام الدورة؛ لا نعدها شهادة Cisco مهنية', price='مجاني', aid=0, url='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html'),
    dict(slug='cisco-networking-basics', title='Cisco Networking Academy — Networking Basics', platform='cisco-networking-academy', description='دورة Cisco مجانية ذاتية التعلم لفهم أساسيات الشبكات، مناسبة للطالب الذي يريد بناء قاعدة قبل التخصص في الشبكات أو الأمن السيبراني.', category='الشبكات', level='مبتدئ', language='الإنجليزية', duration='حسب المسار', free=1, cert=0, cert_type='إتمام الدورة؛ CCNA امتحان منفصل', price='مجاني', aid=0, url='https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html'),
]

def upsert_platform(conn, p):
    conn.execute('''INSERT INTO platforms (slug,name,description,official_url,courses_url,certificates_url,scholarships_url,volunteering_url,country,categories,free_courses_available,certificates_available,financial_aid_available,free_access_guide,official_source,verified,last_checked)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,official_url=excluded.official_url,courses_url=excluded.courses_url,certificates_url=excluded.certificates_url,country=excluded.country,categories=excluded.categories,free_courses_available=excluded.free_courses_available,certificates_available=excluded.certificates_available,free_access_guide=excluded.free_access_guide,official_source=excluded.official_source,verified=1,last_checked=excluded.last_checked''',
    (p['slug'],p['name'],p['description'],p['official_url'],p['courses_url'],p['certificates_url'],p['official_url'],p['official_url'],p['country'],json.dumps(p['categories'],ensure_ascii=False),p['free_courses_available'],p['certificates_available'],p['financial_aid_available'],p['free_access_guide'],p['source'],1,TODAY))

def run():
    conn=sqlite3.connect(DB_PATH)
    conn.execute('PRAGMA foreign_keys=ON')
    for p in PLATFORMS: upsert_platform(conn,p)
    for c in COURSES:
        pid=conn.execute('SELECT id FROM platforms WHERE slug=?',(c['platform'],)).fetchone()[0]
        conn.execute('''INSERT INTO courses (slug,title,platform_id,description,category,level,language,duration,free,certificate_available,certificate_type,price,financial_aid,official_url,source,source_type,verified,status,last_checked)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,platform_id=excluded.platform_id,description=excluded.description,category=excluded.category,level=excluded.level,language=excluded.language,duration=excluded.duration,free=excluded.free,certificate_available=excluded.certificate_available,certificate_type=excluded.certificate_type,price=excluded.price,financial_aid=excluded.financial_aid,official_url=excluded.official_url,source=excluded.source,source_type='official',verified=1,status='open',last_checked=excluded.last_checked''',
        (c['slug'],c['title'],pid,c['description'],c['category'],c['level'],c['language'],c['duration'],c['free'],c['cert'],c['cert_type'],c['price'],c['aid'],c['url'],c['url'],'official',1,'open',TODAY))
    # Correct earlier records that incorrectly represented paid Google Career Certificates as universally free.
    paid_google_slugs=['plus-course-026','plus-course-027','plus-course-028','plus-course-029','plus-course-030','plus-course-031','plus-course-126','plus-course-127','coursera-google-data-analytics','coursera-google-cybersecurity']
    for slug in paid_google_slugs:
        conn.execute("UPDATE courses SET free=0, price='اشتراك مدفوع؛ قد يتوفر Financial Aid عبر Coursera حسب الأهلية', financial_aid=1, certificate_type='Google Career Certificate عبر Coursera/Google Career Skills', last_checked=? WHERE slug=?", (TODAY,slug))
    conn.commit(); conn.close()
    print('Added/updated verified brand courses and corrected Google Career Certificate pricing.')

if __name__=='__main__': run()
